$axure.loadCurrentPage({
  "url":"修改记录_gara.html",
  "generationDate":new Date(1467963156649.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"654f4552a7744b2e9416a6fcdfb07967",
    "type":"Axure:Page",
    "name":"修改记录@Gara",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"410f017e79214378be47e5c8120677bb",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":30},
            "size":{
              "width":1000,
              "height":432}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf58140cba294e469b24707352292e0b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb17a48633af472b9a8721b8e1660e0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u1.png"}},
{
              "id":"111f22fb83c741459fbce8ca7852b878",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c68a73f9473647ef9c3da63d22f13ea0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u1.png"}},
{
              "id":"f699b72d7c1a4478916f90a96a34e13f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":402},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"077d425971e445b0bc8c7961ac385482",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":402},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u43.png"}},
{
              "id":"27391848002144deaf8d9598c3251c51",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":0},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc208158e33247e1a609be04eeba7877",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":0},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u3.png"}},
{
              "id":"1c011f936a354de18400bac511588003",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":30},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4877afdabe9544f7a08607e855fad2dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":30},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u3.png"}},
{
              "id":"beaa5c1d861d4538ad017993eb2411c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":402},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03db5202836447f6924e13824494cc3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":402},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u45.png"}},
{
              "id":"9e426a4625fc42c7a5359f42ebfe06c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":0},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"afb60dfe5d894d97ba059f0d10e2be28",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":0},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u5.png"}},
{
              "id":"e9880d60541b492c9e3ca939cfafaf86",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":30},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44b20e6b789d49c0853f53414d0dfc0b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":30},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u5.png"}},
{
              "id":"3163f93a95844728a39abce0493c2364",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":402},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c14bad3afe74f7484776c0135c05970",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":402},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u47.png"}},
{
              "id":"95baa0a644ce420598c51fc68659e033",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":342},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4f8c7909c694166b2a14a64a8f835b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":342},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u1.png"}},
{
              "id":"9172c224713f4b6da837442b566dd4d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":342},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93e563dfb9564241820b9df84e616316",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":342},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u3.png"}},
{
              "id":"49a0d45e26974950838cc512ab7b6f16",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":342},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac75bca5a3b645f58ede4b6735c01061",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":342},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u5.png"}},
{
              "id":"76e2497797734e048cb5d1e0c9c74130",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":161,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de7b2ac7adae41f3982e8df13df4dbb6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":161,
                      "height":83},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u13.png"}},
{
              "id":"78d5eab2e389436280d90074bf0a6383",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":60},
                "size":{
                  "width":700,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e662cc862bd45ddba85c2024b8c6e8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":60},
                    "size":{
                      "width":700,
                      "height":83},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u15.png"}},
{
              "id":"83c282d0de5b459ea2d0fbbb196f4889",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":60},
                "size":{
                  "width":139,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b108833b826e48f4ab994e8f28d91a7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":60},
                    "size":{
                      "width":139,
                      "height":83},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u17.png"}},
{
              "id":"226d9399109542e6815e5b0cee96551b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":299},
                "size":{
                  "width":161,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c506e485c3314dc6ab02b51e3b59409b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":299},
                    "size":{
                      "width":161,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u25.png"}},
{
              "id":"16abf2aa667744d88a7d2dcd892b0507",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":299},
                "size":{
                  "width":700,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44348c46f5fe42809c9d5a452dc3bb52",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":299},
                    "size":{
                      "width":700,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u27.png"}},
{
              "id":"b2b798238c3d4044bbacd937f196a1ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":299},
                "size":{
                  "width":139,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e13df357dd24ed3ae07ba244d0e2060",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":299},
                    "size":{
                      "width":139,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u29.png"}},
{
              "id":"85cea73041f447ffa45eabdf0d37d54b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":143},
                "size":{
                  "width":161,
                  "height":156},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8bfcbe1e5a8642f1b80b16200a0b394c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":143},
                    "size":{
                      "width":161,
                      "height":156},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u19.png"}},
{
              "id":"e2f8312a6d3f45c091f9d622f16ed2f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":143},
                "size":{
                  "width":700,
                  "height":156},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bafd608882044fb097d50914af512de9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":143},
                    "size":{
                      "width":700,
                      "height":156},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u21.png"}},
{
              "id":"d152169713b040b68e4838d99e49f751",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":143},
                "size":{
                  "width":139,
                  "height":156},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77fe8f6c59ea45bc94e4b7e9b5ccbbb6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":143},
                    "size":{
                      "width":139,
                      "height":156},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u23.png"}},
{
              "id":"d35ee2092ea6469f9c081e50aaa109c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":372},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2412d0ee412846b7a33b9d93fbae6640",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":372},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u1.png"}},
{
              "id":"9f82bea3b9bc434d9e0f750376e0c7a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":372},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9eec093890234bd9b02818680d1389cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":372},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u3.png"}},
{
              "id":"b5caa975c0254cdb887b79723e7053ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":372},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b06a1f1ecfe44d958546c1c086f18a1a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":372},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录_gara/u5.png"}}]},
{
          "id":"376d0ef04f9341e6b2799fe1b276ccd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":280,
              "y":100},
            "size":{
              "width":640,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78d380fca4b44432b5ad4a1ef8d48c98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":100},
                "size":{
                  "width":640,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1baded42ac524db490d8fcb0315e7246",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":280,
              "y":183},
            "size":{
              "width":640,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aaec2e4a97142d58e343e7c03d7e78a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":183},
                "size":{
                  "width":640,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25dc4dc3a2cb46e0ad87c000c903f935",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":488},
            "size":{
              "width":1042,
              "height":762}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039942cb290d4398b98634982873fda9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":488},
                "size":{
                  "width":1042,
                  "height":762}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改记录_gara/u53.png"}},
{
          "id":"264ac14b7f384deeb6886787d0e2c0c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":101.5,
              "y":1260},
            "size":{
              "width":1039,
              "height":196}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"898001f611594e86bdc79afdd7834939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101.5,
                  "y":1260},
                "size":{
                  "width":1039,
                  "height":196}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改记录_gara/u55.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "410f017e79214378be47e5c8120677bb":{
      "scriptId":"u0"},
    "cf58140cba294e469b24707352292e0b":{
      "scriptId":"u1"},
    "fb17a48633af472b9a8721b8e1660e0d":{
      "scriptId":"u2"},
    "27391848002144deaf8d9598c3251c51":{
      "scriptId":"u3"},
    "bc208158e33247e1a609be04eeba7877":{
      "scriptId":"u4"},
    "9e426a4625fc42c7a5359f42ebfe06c3":{
      "scriptId":"u5"},
    "afb60dfe5d894d97ba059f0d10e2be28":{
      "scriptId":"u6"},
    "111f22fb83c741459fbce8ca7852b878":{
      "scriptId":"u7"},
    "c68a73f9473647ef9c3da63d22f13ea0":{
      "scriptId":"u8"},
    "1c011f936a354de18400bac511588003":{
      "scriptId":"u9"},
    "4877afdabe9544f7a08607e855fad2dc":{
      "scriptId":"u10"},
    "e9880d60541b492c9e3ca939cfafaf86":{
      "scriptId":"u11"},
    "44b20e6b789d49c0853f53414d0dfc0b":{
      "scriptId":"u12"},
    "76e2497797734e048cb5d1e0c9c74130":{
      "scriptId":"u13"},
    "de7b2ac7adae41f3982e8df13df4dbb6":{
      "scriptId":"u14"},
    "78d5eab2e389436280d90074bf0a6383":{
      "scriptId":"u15"},
    "7e662cc862bd45ddba85c2024b8c6e8a":{
      "scriptId":"u16"},
    "83c282d0de5b459ea2d0fbbb196f4889":{
      "scriptId":"u17"},
    "b108833b826e48f4ab994e8f28d91a7e":{
      "scriptId":"u18"},
    "85cea73041f447ffa45eabdf0d37d54b":{
      "scriptId":"u19"},
    "8bfcbe1e5a8642f1b80b16200a0b394c":{
      "scriptId":"u20"},
    "e2f8312a6d3f45c091f9d622f16ed2f5":{
      "scriptId":"u21"},
    "bafd608882044fb097d50914af512de9":{
      "scriptId":"u22"},
    "d152169713b040b68e4838d99e49f751":{
      "scriptId":"u23"},
    "77fe8f6c59ea45bc94e4b7e9b5ccbbb6":{
      "scriptId":"u24"},
    "226d9399109542e6815e5b0cee96551b":{
      "scriptId":"u25"},
    "c506e485c3314dc6ab02b51e3b59409b":{
      "scriptId":"u26"},
    "16abf2aa667744d88a7d2dcd892b0507":{
      "scriptId":"u27"},
    "44348c46f5fe42809c9d5a452dc3bb52":{
      "scriptId":"u28"},
    "b2b798238c3d4044bbacd937f196a1ea":{
      "scriptId":"u29"},
    "3e13df357dd24ed3ae07ba244d0e2060":{
      "scriptId":"u30"},
    "95baa0a644ce420598c51fc68659e033":{
      "scriptId":"u31"},
    "f4f8c7909c694166b2a14a64a8f835b0":{
      "scriptId":"u32"},
    "9172c224713f4b6da837442b566dd4d5":{
      "scriptId":"u33"},
    "93e563dfb9564241820b9df84e616316":{
      "scriptId":"u34"},
    "49a0d45e26974950838cc512ab7b6f16":{
      "scriptId":"u35"},
    "ac75bca5a3b645f58ede4b6735c01061":{
      "scriptId":"u36"},
    "d35ee2092ea6469f9c081e50aaa109c3":{
      "scriptId":"u37"},
    "2412d0ee412846b7a33b9d93fbae6640":{
      "scriptId":"u38"},
    "9f82bea3b9bc434d9e0f750376e0c7a7":{
      "scriptId":"u39"},
    "9eec093890234bd9b02818680d1389cb":{
      "scriptId":"u40"},
    "b5caa975c0254cdb887b79723e7053ec":{
      "scriptId":"u41"},
    "b06a1f1ecfe44d958546c1c086f18a1a":{
      "scriptId":"u42"},
    "f699b72d7c1a4478916f90a96a34e13f":{
      "scriptId":"u43"},
    "077d425971e445b0bc8c7961ac385482":{
      "scriptId":"u44"},
    "beaa5c1d861d4538ad017993eb2411c7":{
      "scriptId":"u45"},
    "03db5202836447f6924e13824494cc3d":{
      "scriptId":"u46"},
    "3163f93a95844728a39abce0493c2364":{
      "scriptId":"u47"},
    "4c14bad3afe74f7484776c0135c05970":{
      "scriptId":"u48"},
    "376d0ef04f9341e6b2799fe1b276ccd5":{
      "scriptId":"u49"},
    "78d380fca4b44432b5ad4a1ef8d48c98":{
      "scriptId":"u50"},
    "1baded42ac524db490d8fcb0315e7246":{
      "scriptId":"u51"},
    "2aaec2e4a97142d58e343e7c03d7e78a":{
      "scriptId":"u52"},
    "25dc4dc3a2cb46e0ad87c000c903f935":{
      "scriptId":"u53"},
    "039942cb290d4398b98634982873fda9":{
      "scriptId":"u54"},
    "264ac14b7f384deeb6886787d0e2c0c5":{
      "scriptId":"u55"},
    "898001f611594e86bdc79afdd7834939":{
      "scriptId":"u56"}}});