$axure.loadCurrentPage({
  "url":"05-2使用帮助.html",
  "generationDate":new Date(1467963171632),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"c546e7a691f04c998a2756df69537eb5",
    "type":"Axure:Page",
    "name":"05-2使用帮助",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"023fe228896342caa5385035b0c40a9c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-7,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"b60f5b15b15446d2bb3c7cbb2d76f50d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":16},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6babadef9e484ee8a08b6d72704f9057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":16},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fada28b49994474da506eb35e5dd9c56":{
      "packageId":"fada28b49994474da506eb35e5dd9c56",
      "type":"Axure:Master",
      "name":"底板（子页面）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a9f3c03e12c14394b49605490f5380f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":320,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ad1cc80c89a41acb906c231c2c6d55d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":320,
                    "height":15},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u11.png"}},
{
            "id":"5cbfd378f7fd49ae8ae8978e0b82dfe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8facad6e6d6d41ae94a2911bd72e2a82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u13.png"}},
{
            "id":"8e4635a390004c6f9d4539508bb6597c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c86faa2ccad4c689fee1a5797cdca32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u15.png"}},
{
            "id":"68932766f7d6416fb1efa9fda7953413",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":-7,
                "y":10},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eca5c557fc884ac0b9c52ed5bc5bd886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":-7,
                    "y":10},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/01-2__/u9.png"}}]}}},
  "objectPaths":{
    "023fe228896342caa5385035b0c40a9c":{
      "scriptId":"u0",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u1"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u2"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u3"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u4"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u5"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u6"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u7"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u8"}},
    "b60f5b15b15446d2bb3c7cbb2d76f50d":{
      "scriptId":"u9"},
    "6babadef9e484ee8a08b6d72704f9057":{
      "scriptId":"u10"}}});