$axure.loadCurrentPage({
  "url":"16-2已处理违章（车辆列表）.html",
  "generationDate":new Date(1467963170748.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"ef2267691aef4286819856c5d09a52d2",
    "type":"Axure:Page",
    "name":"16-2已处理违章（车辆列表）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"67ac01bf3b42484c89ebd9bf6c98da9f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-7,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"08ff4e3f88574928b0ba7c3c652fc2e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":16},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d497a5dc12704298aa30c6f81ee4cb89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":16},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4637230ea8c742b78e6250fbaf8aa3df",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50}},
          "adaptiveStyles":{
},
          "masterId":"74a47c96c1724d02bbc89305444ec62d"},
{
          "id":"e3ada5122ee043cfaefacf34b12ebc5e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100}},
          "adaptiveStyles":{
},
          "masterId":"74a47c96c1724d02bbc89305444ec62d"},
{
          "id":"70a53ab235c1403cbf6b5b225942538d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":150}},
          "adaptiveStyles":{
},
          "masterId":"74a47c96c1724d02bbc89305444ec62d"},
{
          "id":"4e7183bedecd441b8fd2b53ed7519a00",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":200}},
          "adaptiveStyles":{
},
          "masterId":"74a47c96c1724d02bbc89305444ec62d"},
{
          "id":"05adb784ea2242569ca9a410af59eeef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":10,
              "y":620},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"935472211b5049718ad36bc89aaa80d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":10,
                  "y":620},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u19.png"}},
{
          "id":"ab3edfb0a07849ce962314cf5e09631b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":597},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bff5807240346a6a769182d546751d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":597},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"7144eca4949f41e9a8c2f1191a7e1b40",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":597},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c2507ec56934b288dccb0f54310d063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":597},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fada28b49994474da506eb35e5dd9c56":{
      "packageId":"fada28b49994474da506eb35e5dd9c56",
      "type":"Axure:Master",
      "name":"底板（子页面）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a9f3c03e12c14394b49605490f5380f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":320,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ad1cc80c89a41acb906c231c2c6d55d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":320,
                    "height":15},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u11.png"}},
{
            "id":"5cbfd378f7fd49ae8ae8978e0b82dfe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8facad6e6d6d41ae94a2911bd72e2a82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u13.png"}},
{
            "id":"8e4635a390004c6f9d4539508bb6597c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c86faa2ccad4c689fee1a5797cdca32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u15.png"}},
{
            "id":"68932766f7d6416fb1efa9fda7953413",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":-7,
                "y":10},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eca5c557fc884ac0b9c52ed5bc5bd886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":-7,
                    "y":10},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/01-2__/u9.png"}}]}},
    "74a47c96c1724d02bbc89305444ec62d":{
      "packageId":"74a47c96c1724d02bbc89305444ec62d",
      "type":"Axure:Master",
      "name":"已处理违章（车辆）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"4404549c91764d689d541d7bccf855a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":110},
              "size":{
                "width":300,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb83486654904bf2af9b6b97b7437fd2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":110},
                  "size":{
                    "width":300,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/16-2已处理违章（车辆列表）/u12.png",
              "normal~":"images/16-2已处理违章（车辆列表）/u12.png",
              "normal~":"images/16-2已处理违章（车辆列表）/u12.png",
              "normal~":"images/16-2已处理违章（车辆列表）/u12.png"}},
{
            "id":"296793c07c9648008af1739ee824ba7e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"12px",
              "fontWeight":"700",
              "location":{
                "x":20,
                "y":120},
              "size":{
                "width":200,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94d84d0a205e40b9ae8644ee79e017e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "location":{
                    "x":20,
                    "y":120},
                  "size":{
                    "width":200,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cafe1f76cf884cb9a9a190711500cec3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "horizontalAlignment":"right",
              "location":{
                "x":120,
                "y":120},
              "size":{
                "width":180,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3cea96c8b5e94499821b4937046a39a6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":120,
                    "y":120},
                  "size":{
                    "width":180,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ba80b77cb5b84bd9bae1143fde92eeff",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":110},
              "size":{
                "width":320,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 17-2已处理违章（违章列表）",
                        "target":{
                          "targetType":"page",
                          "url":"17-2已处理违章（违章列表）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "67ac01bf3b42484c89ebd9bf6c98da9f":{
      "scriptId":"u0",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u1"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u2"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u3"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u4"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u5"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u6"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u7"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u8"}},
    "08ff4e3f88574928b0ba7c3c652fc2e3":{
      "scriptId":"u9"},
    "d497a5dc12704298aa30c6f81ee4cb89":{
      "scriptId":"u10"},
    "4637230ea8c742b78e6250fbaf8aa3df":{
      "scriptId":"u11",
      "4404549c91764d689d541d7bccf855a9":{
        "scriptId":"u12"},
      "bb83486654904bf2af9b6b97b7437fd2":{
        "scriptId":"u13"},
      "296793c07c9648008af1739ee824ba7e":{
        "scriptId":"u14"},
      "94d84d0a205e40b9ae8644ee79e017e3":{
        "scriptId":"u15"},
      "cafe1f76cf884cb9a9a190711500cec3":{
        "scriptId":"u16"},
      "3cea96c8b5e94499821b4937046a39a6":{
        "scriptId":"u17"},
      "ba80b77cb5b84bd9bae1143fde92eeff":{
        "scriptId":"u18"}},
    "e3ada5122ee043cfaefacf34b12ebc5e":{
      "scriptId":"u19",
      "4404549c91764d689d541d7bccf855a9":{
        "scriptId":"u20"},
      "bb83486654904bf2af9b6b97b7437fd2":{
        "scriptId":"u21"},
      "296793c07c9648008af1739ee824ba7e":{
        "scriptId":"u22"},
      "94d84d0a205e40b9ae8644ee79e017e3":{
        "scriptId":"u23"},
      "cafe1f76cf884cb9a9a190711500cec3":{
        "scriptId":"u24"},
      "3cea96c8b5e94499821b4937046a39a6":{
        "scriptId":"u25"},
      "ba80b77cb5b84bd9bae1143fde92eeff":{
        "scriptId":"u26"}},
    "70a53ab235c1403cbf6b5b225942538d":{
      "scriptId":"u27",
      "4404549c91764d689d541d7bccf855a9":{
        "scriptId":"u28"},
      "bb83486654904bf2af9b6b97b7437fd2":{
        "scriptId":"u29"},
      "296793c07c9648008af1739ee824ba7e":{
        "scriptId":"u30"},
      "94d84d0a205e40b9ae8644ee79e017e3":{
        "scriptId":"u31"},
      "cafe1f76cf884cb9a9a190711500cec3":{
        "scriptId":"u32"},
      "3cea96c8b5e94499821b4937046a39a6":{
        "scriptId":"u33"},
      "ba80b77cb5b84bd9bae1143fde92eeff":{
        "scriptId":"u34"}},
    "4e7183bedecd441b8fd2b53ed7519a00":{
      "scriptId":"u35",
      "4404549c91764d689d541d7bccf855a9":{
        "scriptId":"u36"},
      "bb83486654904bf2af9b6b97b7437fd2":{
        "scriptId":"u37"},
      "296793c07c9648008af1739ee824ba7e":{
        "scriptId":"u38"},
      "94d84d0a205e40b9ae8644ee79e017e3":{
        "scriptId":"u39"},
      "cafe1f76cf884cb9a9a190711500cec3":{
        "scriptId":"u40"},
      "3cea96c8b5e94499821b4937046a39a6":{
        "scriptId":"u41"},
      "ba80b77cb5b84bd9bae1143fde92eeff":{
        "scriptId":"u42"}},
    "05adb784ea2242569ca9a410af59eeef":{
      "scriptId":"u43"},
    "935472211b5049718ad36bc89aaa80d0":{
      "scriptId":"u44"},
    "ab3edfb0a07849ce962314cf5e09631b":{
      "scriptId":"u45"},
    "0bff5807240346a6a769182d546751d5":{
      "scriptId":"u46"},
    "7144eca4949f41e9a8c2f1191a7e1b40":{
      "scriptId":"u47"},
    "8c2507ec56934b288dccb0f54310d063":{
      "scriptId":"u48"}}});