$axure.loadCurrentPage({
  "url":"12-2我的驾驶证.html",
  "generationDate":new Date(1467963170147.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"2693545f51294af293c8539e5a7602c7",
    "type":"Axure:Page",
    "name":"12-2我的驾驶证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ff7528b1fea494981cc518e604ae7cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":1020},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a85967814d9446eabe2bd5f846a8534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":1020},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/12-2我的驾驶证/u0.png"}},
{
          "id":"543db04cb56b461d8f40c29b00f67974",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-7,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"761940b3e0c6479f8783c1f21990e1be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":16},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"418adfe509674f6bb8d4cdba7a8f7177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":16},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec5754a09bb647c3acdb1f48bf3f51dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":12},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d3bd182c64a46c4afa6e414647da526",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":12},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 13-3添加/修改驾驶证",
                      "target":{
                        "targetType":"page",
                        "url":"13-3添加_修改驾驶证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/08-2我的爱车/u39.png"}},
{
          "id":"93893cd7c1b84496a3a0fce4a3e067ef",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":49}},
          "adaptiveStyles":{
},
          "masterId":"4e92085f1896457cb8698f142e32d544"},
{
          "id":"1048e9e625204d4dbccb2b59f705151c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":89}},
          "adaptiveStyles":{
},
          "masterId":"4e92085f1896457cb8698f142e32d544"},
{
          "id":"9b149315170f4406b215fedf073252c0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":129}},
          "adaptiveStyles":{
},
          "masterId":"4e92085f1896457cb8698f142e32d544"},
{
          "id":"cf40a8b290a84bc2be21f472ba878594",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":600},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7386e50d005e45ad8c8a18dd2cc58644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":600},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"1d9f7400c46344f0b85cbf55dfee598a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":10,
              "y":620},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31bc2848b1d140b4882f20c55717e980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":10,
                  "y":620},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u19.png"}},
{
          "id":"a37f65d81e5f4985a1a2593600c91a59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":410,
              "y":822},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cca995d1d2d74b69a60ce44198468b5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":410,
                  "y":822},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c989b2953904629a41b92d2255cc750",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":465,
              "y":852},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1d55f8d651f428fa547f4106b6c86ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":465,
                  "y":852},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d9838ddb4914437b8faa4a32f9bc9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":410,
              "y":852},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ff41b66ba1142dcb418edb1b8a0ba40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":852},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9079d894849f4ad1ad22cbe5506f9c34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":410,
              "y":900},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"994a61955ad34599978aea7b02419a83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":410,
                  "y":900},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d478a502c3dd47a68079a3a7eb412957",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":465,
              "y":940},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c47cdc137acf4d559657c0c00f285e66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":465,
                  "y":940},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7cb7c2937614377a69b6332a30febff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":410,
              "y":940},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aaad3577e6f406b8a9009539067e6e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":940},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69ba6a638cf642b2a650cd89a789db38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":410,
              "y":980},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98516728a15049c79a48ebea21854893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":410,
                  "y":980},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62dc2a769da4423c9ad4232693b03280",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":80,
              "y":689},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392a6c496fc1448cb2d0ba9bf0c2d789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":80,
                  "y":689},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c23359064df493b9787c3af605559cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":660},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce186dd0a3b74a67a6bb6481df3ecc51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":660},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50f672f6d17e4c5ea0c4df8e1398a3b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF66CC},
            "location":{
              "x":80,
              "y":727},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52223fa5936a4ff0b15e9a286ef7ab16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF66CC},
                "location":{
                  "x":80,
                  "y":727},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-1违章处理首页/u249.png"}},
{
          "id":"5bf79a289eba49e8b5996b1bbe368935",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":160,
              "y":727},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10f302feef244af0b5492983dfddaa74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":160,
                  "y":727},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f63753794f94f018cb797786a80a255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":10,
              "y":690},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed3a83a394c045848480fda1d5acd34b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":690},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb3e03baa3eb420d87a65f7e09d5fe9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":800,
              "y":620},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7da982d303d4ee1b79918ee3c5fcccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":800,
                  "y":620},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u19.png"}},
{
          "id":"11e6a2c3ad2144e7a91597dfdffedaa9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":690},
            "size":{
              "width":352,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"919710e8b4fb4468965b27c80e0af006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":690},
                "size":{
                  "width":352,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/08-2我的爱车/u106.png"}},
{
          "id":"d284abecd4264353b6a25d6d07697bc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":820,
              "y":710},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a012f7fd1b514e99bace81d0ea7d943f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":820,
                  "y":710},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa837da8c28e4c38b144ff77afc330a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":890,
              "y":741},
            "size":{
              "width":174,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ada00fabf8ea4a4b8f8b87e59c409354",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":890,
                  "y":741},
                "size":{
                  "width":174,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ded682f008314625a31a8137de5556a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF66CC},
            "location":{
              "x":970,
              "y":711},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d01c4af19c2c444585c1d9487dce8164",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF66CC},
                "location":{
                  "x":970,
                  "y":711},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u60.png"}},
{
          "id":"ffb5227c9a2c476f9db349b7f3ad88fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":890,
              "y":711},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c590d27f85403995d8015d9414a1ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":890,
                  "y":711},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u74.png"}},
{
          "id":"ea98c883c7344514a455186fcc0efba7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":802,
              "y":900},
            "size":{
              "width":350,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a76b96b853e481986cae41b35d97fae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":802,
                  "y":900},
                "size":{
                  "width":350,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/08-2我的爱车/u116.png"}},
{
          "id":"7595df0512bf47de8f12d86bc7ac7f4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":822,
              "y":916},
            "size":{
              "width":190,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee54af5f57ca4ecba5777c045e306a5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":822,
                  "y":916},
                "size":{
                  "width":190,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a774cddb02b24830b7712d991da2ba0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":982,
              "y":916},
            "size":{
              "width":150,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db10f2e46f54bbc85cbf51b201e0fcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":982,
                  "y":916},
                "size":{
                  "width":150,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"737aa134384e43deb42abcbaf5984b22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF66CC},
            "location":{
              "x":892,
              "y":916},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17c9fa17c9774e5ca085f2d8af96b6ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF66CC},
                "location":{
                  "x":892,
                  "y":916},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u60.png"}},
{
          "id":"a769f6015af245eb991bed841864a01b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":892,
              "y":944},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38b4b5f61ad74a56a193de845b509104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":892,
                  "y":944},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u74.png"}},
{
          "id":"c292e4bf82724da18e144001dc8483f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":982,
              "y":942},
            "size":{
              "width":150,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1cb1ab9ca454441b779e7a5fb51005b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":982,
                  "y":942},
                "size":{
                  "width":150,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29bda14ca75243c4bb060729b58f0796",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":530,
              "y":901.5},
            "size":{
              "width":13,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1184b545187245b9b72c0481830f12cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":530,
                  "y":901.5},
                "size":{
                  "width":13,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-1违章处理首页/u265.png"}},
{
          "id":"122eb17152394d99888fcd5638916bbf",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":543,
              "y":910},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aac9848c2c7240d99b2bab1d67cc87ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":543,
                  "y":910},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"b57dc728321e4ee1884febb3c0e2eee8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":190,
              "y":690},
            "size":{
              "width":13,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49173377283746e6ba11103dc0255d8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":190,
                  "y":690},
                "size":{
                  "width":13,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-1违章处理首页/u265.png"}},
{
          "id":"2cad1f782062466fb5d6accb361d2de1",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":698},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3990c81e41114f428d7515cfdfa26b9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203,
                  "y":698},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"c8573c4afb1043c29f6d720f9c2d5433",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":410,
              "y":1080},
            "size":{
              "width":210,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64c2317997c7413cb39b09fea1b41e3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":1080},
                "size":{
                  "width":210,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"038f8c82abd54a16bb45cd753feb49d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":410,
              "y":1110},
            "size":{
              "width":210,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a2d52a4b00c42eca8dcdd2aa98bfb94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":1110},
                "size":{
                  "width":210,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c101702d21f420ca32f99ddd411f3eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":410,
              "y":1140},
            "size":{
              "width":210,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718354f09eb74d91a815eb90876f95e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":1140},
                "size":{
                  "width":210,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8581c8a1f80b48c699544ce5dd639377",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":1050},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d038b0f2ab304df0a69ffd01023659fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":1050},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"6e51ff4563dc43eeaf2a87c4de74892f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":810}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"653f128c9d9847c7b4b197619f8cbfc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":826},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aa0146ca4a94cb5bf1cbd91521d6df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":80,
                  "y":826},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dad15b444f04231a0799bef975a3989",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":822},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4bc7e450484fb3ad0ba9ffb54d6b10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":822},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 13-3添加/修改驾驶证",
                      "target":{
                        "targetType":"page",
                        "url":"13-3添加_修改驾驶证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/08-2我的爱车/u39.png"}},
{
          "id":"08af302cc23347e290c4e1df6a6dec87",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":859}},
          "adaptiveStyles":{
},
          "masterId":"4e92085f1896457cb8698f142e32d544"},
{
          "id":"832ea28f4bec439cbe0f0ec346051dea",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":899}},
          "adaptiveStyles":{
},
          "masterId":"4e92085f1896457cb8698f142e32d544"},
{
          "id":"814b0b150c5e41faae505ab2398f38e6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":939}},
          "adaptiveStyles":{
},
          "masterId":"4e92085f1896457cb8698f142e32d544"},
{
          "id":"1b3d147f27534503bdd3bd8b54239c9e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":830},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be17002721b349a4b1d885b053e9116e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":830},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"3ad326dfcf4c4dd8ba6dd6e659f21f6d",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":910},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa9fb2f89f9e497685917fe6690a02f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":910},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"45fe3c77e92a4e0b8fab59b93037d0cb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":1020}},
          "adaptiveStyles":{
},
          "masterId":"4e92085f1896457cb8698f142e32d544"},
{
          "id":"b25ec3b569034419aab5dd5945382eb4",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":1040},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"facd18cea7544cd5aa1fa18380108e48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":1040},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "fada28b49994474da506eb35e5dd9c56":{
      "packageId":"fada28b49994474da506eb35e5dd9c56",
      "type":"Axure:Master",
      "name":"底板（子页面）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a9f3c03e12c14394b49605490f5380f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":320,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ad1cc80c89a41acb906c231c2c6d55d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":320,
                    "height":15},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u11.png",
              "normal~":"images/全局说明/u11.png"}},
{
            "id":"5cbfd378f7fd49ae8ae8978e0b82dfe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8facad6e6d6d41ae94a2911bd72e2a82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u13.png",
              "normal~":"images/全局说明/u13.png"}},
{
            "id":"8e4635a390004c6f9d4539508bb6597c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c86faa2ccad4c689fee1a5797cdca32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u15.png",
              "normal~":"images/全局说明/u15.png"}},
{
            "id":"68932766f7d6416fb1efa9fda7953413",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":-7,
                "y":10},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eca5c557fc884ac0b9c52ed5bc5bd886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":-7,
                    "y":10},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/01-2__/u9.png",
              "normal~":"images/01-2__/u9.png"}}]}},
    "4e92085f1896457cb8698f142e32d544":{
      "packageId":"4e92085f1896457cb8698f142e32d544",
      "type":"Axure:Master",
      "name":"我的驾驶证",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e402cf2f85f74f2d80d9b43889b453a0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"12px",
              "fontWeight":"700",
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":300,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"50b2b0d7135e4aa8b3e840646b6ede4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":300,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4cb38207c0fe4bb4b859f8d4b5a70476",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "horizontalAlignment":"right",
              "location":{
                "x":150,
                "y":10},
              "size":{
                "width":160,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dec6a17baef9494898dfb2f0a650b751",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":150,
                    "y":10},
                  "size":{
                    "width":160,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"72634f00dac74360a5d29c3c7f1e1c44",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 13-3添加/修改驾驶证",
                        "target":{
                          "targetType":"page",
                          "url":"13-3添加_修改驾驶证.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "5ff7528b1fea494981cc518e604ae7cc":{
      "scriptId":"u0"},
    "2a85967814d9446eabe2bd5f846a8534":{
      "scriptId":"u1"},
    "543db04cb56b461d8f40c29b00f67974":{
      "scriptId":"u2",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u3"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u4"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u5"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u6"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u7"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u8"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u9"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u10"}},
    "761940b3e0c6479f8783c1f21990e1be":{
      "scriptId":"u11"},
    "418adfe509674f6bb8d4cdba7a8f7177":{
      "scriptId":"u12"},
    "ec5754a09bb647c3acdb1f48bf3f51dd":{
      "scriptId":"u13"},
    "7d3bd182c64a46c4afa6e414647da526":{
      "scriptId":"u14"},
    "93893cd7c1b84496a3a0fce4a3e067ef":{
      "scriptId":"u15",
      "e402cf2f85f74f2d80d9b43889b453a0":{
        "scriptId":"u16"},
      "50b2b0d7135e4aa8b3e840646b6ede4f":{
        "scriptId":"u17"},
      "4cb38207c0fe4bb4b859f8d4b5a70476":{
        "scriptId":"u18"},
      "dec6a17baef9494898dfb2f0a650b751":{
        "scriptId":"u19"},
      "72634f00dac74360a5d29c3c7f1e1c44":{
        "scriptId":"u20"}},
    "1048e9e625204d4dbccb2b59f705151c":{
      "scriptId":"u21",
      "e402cf2f85f74f2d80d9b43889b453a0":{
        "scriptId":"u22"},
      "50b2b0d7135e4aa8b3e840646b6ede4f":{
        "scriptId":"u23"},
      "4cb38207c0fe4bb4b859f8d4b5a70476":{
        "scriptId":"u24"},
      "dec6a17baef9494898dfb2f0a650b751":{
        "scriptId":"u25"},
      "72634f00dac74360a5d29c3c7f1e1c44":{
        "scriptId":"u26"}},
    "9b149315170f4406b215fedf073252c0":{
      "scriptId":"u27",
      "e402cf2f85f74f2d80d9b43889b453a0":{
        "scriptId":"u28"},
      "50b2b0d7135e4aa8b3e840646b6ede4f":{
        "scriptId":"u29"},
      "4cb38207c0fe4bb4b859f8d4b5a70476":{
        "scriptId":"u30"},
      "dec6a17baef9494898dfb2f0a650b751":{
        "scriptId":"u31"},
      "72634f00dac74360a5d29c3c7f1e1c44":{
        "scriptId":"u32"}},
    "cf40a8b290a84bc2be21f472ba878594":{
      "scriptId":"u33"},
    "7386e50d005e45ad8c8a18dd2cc58644":{
      "scriptId":"u34"},
    "1d9f7400c46344f0b85cbf55dfee598a":{
      "scriptId":"u35"},
    "31bc2848b1d140b4882f20c55717e980":{
      "scriptId":"u36"},
    "a37f65d81e5f4985a1a2593600c91a59":{
      "scriptId":"u37"},
    "cca995d1d2d74b69a60ce44198468b5d":{
      "scriptId":"u38"},
    "6c989b2953904629a41b92d2255cc750":{
      "scriptId":"u39"},
    "f1d55f8d651f428fa547f4106b6c86ec":{
      "scriptId":"u40"},
    "9d9838ddb4914437b8faa4a32f9bc9b3":{
      "scriptId":"u41"},
    "4ff41b66ba1142dcb418edb1b8a0ba40":{
      "scriptId":"u42"},
    "9079d894849f4ad1ad22cbe5506f9c34":{
      "scriptId":"u43"},
    "994a61955ad34599978aea7b02419a83":{
      "scriptId":"u44"},
    "d478a502c3dd47a68079a3a7eb412957":{
      "scriptId":"u45"},
    "c47cdc137acf4d559657c0c00f285e66":{
      "scriptId":"u46"},
    "c7cb7c2937614377a69b6332a30febff":{
      "scriptId":"u47"},
    "4aaad3577e6f406b8a9009539067e6e2":{
      "scriptId":"u48"},
    "69ba6a638cf642b2a650cd89a789db38":{
      "scriptId":"u49"},
    "98516728a15049c79a48ebea21854893":{
      "scriptId":"u50"},
    "62dc2a769da4423c9ad4232693b03280":{
      "scriptId":"u51"},
    "392a6c496fc1448cb2d0ba9bf0c2d789":{
      "scriptId":"u52"},
    "4c23359064df493b9787c3af605559cf":{
      "scriptId":"u53"},
    "ce186dd0a3b74a67a6bb6481df3ecc51":{
      "scriptId":"u54"},
    "50f672f6d17e4c5ea0c4df8e1398a3b1":{
      "scriptId":"u55"},
    "52223fa5936a4ff0b15e9a286ef7ab16":{
      "scriptId":"u56"},
    "5bf79a289eba49e8b5996b1bbe368935":{
      "scriptId":"u57"},
    "10f302feef244af0b5492983dfddaa74":{
      "scriptId":"u58"},
    "0f63753794f94f018cb797786a80a255":{
      "scriptId":"u59"},
    "ed3a83a394c045848480fda1d5acd34b":{
      "scriptId":"u60"},
    "bb3e03baa3eb420d87a65f7e09d5fe9c":{
      "scriptId":"u61"},
    "b7da982d303d4ee1b79918ee3c5fcccb":{
      "scriptId":"u62"},
    "11e6a2c3ad2144e7a91597dfdffedaa9":{
      "scriptId":"u63"},
    "919710e8b4fb4468965b27c80e0af006":{
      "scriptId":"u64"},
    "d284abecd4264353b6a25d6d07697bc7":{
      "scriptId":"u65"},
    "a012f7fd1b514e99bace81d0ea7d943f":{
      "scriptId":"u66"},
    "fa837da8c28e4c38b144ff77afc330a8":{
      "scriptId":"u67"},
    "ada00fabf8ea4a4b8f8b87e59c409354":{
      "scriptId":"u68"},
    "ded682f008314625a31a8137de5556a6":{
      "scriptId":"u69"},
    "d01c4af19c2c444585c1d9487dce8164":{
      "scriptId":"u70"},
    "ffb5227c9a2c476f9db349b7f3ad88fb":{
      "scriptId":"u71"},
    "37c590d27f85403995d8015d9414a1ec":{
      "scriptId":"u72"},
    "ea98c883c7344514a455186fcc0efba7":{
      "scriptId":"u73"},
    "9a76b96b853e481986cae41b35d97fae":{
      "scriptId":"u74"},
    "7595df0512bf47de8f12d86bc7ac7f4a":{
      "scriptId":"u75"},
    "ee54af5f57ca4ecba5777c045e306a5b":{
      "scriptId":"u76"},
    "a774cddb02b24830b7712d991da2ba0d":{
      "scriptId":"u77"},
    "4db10f2e46f54bbc85cbf51b201e0fcc":{
      "scriptId":"u78"},
    "737aa134384e43deb42abcbaf5984b22":{
      "scriptId":"u79"},
    "17c9fa17c9774e5ca085f2d8af96b6ae":{
      "scriptId":"u80"},
    "a769f6015af245eb991bed841864a01b":{
      "scriptId":"u81"},
    "38b4b5f61ad74a56a193de845b509104":{
      "scriptId":"u82"},
    "c292e4bf82724da18e144001dc8483f1":{
      "scriptId":"u83"},
    "f1cb1ab9ca454441b779e7a5fb51005b":{
      "scriptId":"u84"},
    "29bda14ca75243c4bb060729b58f0796":{
      "scriptId":"u85"},
    "1184b545187245b9b72c0481830f12cd":{
      "scriptId":"u86"},
    "122eb17152394d99888fcd5638916bbf":{
      "scriptId":"u87"},
    "aac9848c2c7240d99b2bab1d67cc87ae":{
      "scriptId":"u88"},
    "b57dc728321e4ee1884febb3c0e2eee8":{
      "scriptId":"u89"},
    "49173377283746e6ba11103dc0255d8b":{
      "scriptId":"u90"},
    "2cad1f782062466fb5d6accb361d2de1":{
      "scriptId":"u91"},
    "3990c81e41114f428d7515cfdfa26b9a":{
      "scriptId":"u92"},
    "c8573c4afb1043c29f6d720f9c2d5433":{
      "scriptId":"u93"},
    "64c2317997c7413cb39b09fea1b41e3a":{
      "scriptId":"u94"},
    "038f8c82abd54a16bb45cd753feb49d9":{
      "scriptId":"u95"},
    "7a2d52a4b00c42eca8dcdd2aa98bfb94":{
      "scriptId":"u96"},
    "2c101702d21f420ca32f99ddd411f3eb":{
      "scriptId":"u97"},
    "718354f09eb74d91a815eb90876f95e7":{
      "scriptId":"u98"},
    "8581c8a1f80b48c699544ce5dd639377":{
      "scriptId":"u99"},
    "d038b0f2ab304df0a69ffd01023659fe":{
      "scriptId":"u100"},
    "6e51ff4563dc43eeaf2a87c4de74892f":{
      "scriptId":"u101",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u102"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u103"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u104"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u105"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u106"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u107"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u108"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u109"}},
    "653f128c9d9847c7b4b197619f8cbfc8":{
      "scriptId":"u110"},
    "5aa0146ca4a94cb5bf1cbd91521d6df4":{
      "scriptId":"u111"},
    "2dad15b444f04231a0799bef975a3989":{
      "scriptId":"u112"},
    "1a4bc7e450484fb3ad0ba9ffb54d6b10":{
      "scriptId":"u113"},
    "08af302cc23347e290c4e1df6a6dec87":{
      "scriptId":"u114",
      "e402cf2f85f74f2d80d9b43889b453a0":{
        "scriptId":"u115"},
      "50b2b0d7135e4aa8b3e840646b6ede4f":{
        "scriptId":"u116"},
      "4cb38207c0fe4bb4b859f8d4b5a70476":{
        "scriptId":"u117"},
      "dec6a17baef9494898dfb2f0a650b751":{
        "scriptId":"u118"},
      "72634f00dac74360a5d29c3c7f1e1c44":{
        "scriptId":"u119"}},
    "832ea28f4bec439cbe0f0ec346051dea":{
      "scriptId":"u120",
      "e402cf2f85f74f2d80d9b43889b453a0":{
        "scriptId":"u121"},
      "50b2b0d7135e4aa8b3e840646b6ede4f":{
        "scriptId":"u122"},
      "4cb38207c0fe4bb4b859f8d4b5a70476":{
        "scriptId":"u123"},
      "dec6a17baef9494898dfb2f0a650b751":{
        "scriptId":"u124"},
      "72634f00dac74360a5d29c3c7f1e1c44":{
        "scriptId":"u125"}},
    "814b0b150c5e41faae505ab2398f38e6":{
      "scriptId":"u126",
      "e402cf2f85f74f2d80d9b43889b453a0":{
        "scriptId":"u127"},
      "50b2b0d7135e4aa8b3e840646b6ede4f":{
        "scriptId":"u128"},
      "4cb38207c0fe4bb4b859f8d4b5a70476":{
        "scriptId":"u129"},
      "dec6a17baef9494898dfb2f0a650b751":{
        "scriptId":"u130"},
      "72634f00dac74360a5d29c3c7f1e1c44":{
        "scriptId":"u131"}},
    "1b3d147f27534503bdd3bd8b54239c9e":{
      "scriptId":"u132"},
    "be17002721b349a4b1d885b053e9116e":{
      "scriptId":"u133"},
    "3ad326dfcf4c4dd8ba6dd6e659f21f6d":{
      "scriptId":"u134"},
    "aa9fb2f89f9e497685917fe6690a02f6":{
      "scriptId":"u135"},
    "45fe3c77e92a4e0b8fab59b93037d0cb":{
      "scriptId":"u136",
      "e402cf2f85f74f2d80d9b43889b453a0":{
        "scriptId":"u137"},
      "50b2b0d7135e4aa8b3e840646b6ede4f":{
        "scriptId":"u138"},
      "4cb38207c0fe4bb4b859f8d4b5a70476":{
        "scriptId":"u139"},
      "dec6a17baef9494898dfb2f0a650b751":{
        "scriptId":"u140"},
      "72634f00dac74360a5d29c3c7f1e1c44":{
        "scriptId":"u141"}},
    "b25ec3b569034419aab5dd5945382eb4":{
      "scriptId":"u142"},
    "facd18cea7544cd5aa1fa18380108e48":{
      "scriptId":"u143"}}});