$axure.loadCurrentPage({
  "url":"01-2代办处理.html",
  "generationDate":new Date(1467963163112.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"b190eaa712d94b738211bf08dd98ba02",
    "type":"Axure:Page",
    "name":"01-2代办处理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3c07271c6a0c4389a4ccb003f7f42a5d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-7,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"0afef41b9242452d84e9f2cb468dda22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":15},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f805f80fbfd848a58df23a54d145f796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":15},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db5068096e274fd4b133b5abf1c4014a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":414},
            "size":{
              "width":320,
              "height":76},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a61d516685a49f8b946cfaaa2dc86c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":414},
                "size":{
                  "width":320,
                  "height":76},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2代办处理/u11.png"}},
{
          "id":"12122c7b65144865abfb252699103cb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":10,
              "y":450},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d05a1846b834464185a4a0948d8e86ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":10,
                  "y":450},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 02-2选择代办商家",
                      "target":{
                        "targetType":"page",
                        "url":"02-2选择代办商家.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/02-0第一次进入/u25.png"}},
{
          "id":"d79c19344dac46f3a4887e4c51f8477c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":600},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcb88a93feae4fd1a973d9fa5a5da37e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":600},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"545b9f0fbe7c407bbb458b939f7df490",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":300,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cc246445fdd4982bea85ecaae38b032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":300,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77b6057b206b4893b4712c7aa7d3f5da",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":80}},
          "adaptiveStyles":{
},
          "masterId":"a2d1524f0a4d4be482cb8aeae8d7497e"},
{
          "id":"bc78dd7ef47f4ff98ca333ea211d4807",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":194}},
          "adaptiveStyles":{
},
          "masterId":"a2d1524f0a4d4be482cb8aeae8d7497e"},
{
          "id":"f0e6c40e750a41d897e5abdbfa9ca317",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":310}},
          "adaptiveStyles":{
},
          "masterId":"a2d1524f0a4d4be482cb8aeae8d7497e"},
{
          "id":"34b68e108bbd41f3b3590afcfd05eaea",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":414},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}},
{
          "id":"70ca83c73a3c42faa81d1b192668075f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":140,
              "y":426},
            "size":{
              "width":70,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd9f6beebc7b45aa93d201f5b2faf7f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":426},
                "size":{
                  "width":70,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"072b77e3371e4003a01465f8aae31071",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":195,
              "y":426},
            "size":{
              "width":70,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42f8e0a6a9a140f8b778fc12b41ffc33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":195,
                  "y":426},
                "size":{
                  "width":70,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee4b72cfe01f44c588eee1ff94cce7fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":235,
              "y":426},
            "size":{
              "width":70,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9bc0152ad654715a7c81b3bdf2938d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":426},
                "size":{
                  "width":70,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b10af99dc44f44a0b7e75cbb1a6f9020",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":423},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5642c679edb64c7f8a340fac02ed07dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":423},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ddc41c026e404941b182db54ca8909aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":30,
              "y":423},
            "size":{
              "width":50,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19a3058d051e4345bc13ae7f36b91b19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":30,
                  "y":423},
                "size":{
                  "width":50,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"452727b8b0714be3b02bdb7a0a676593",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":10,
              "y":630},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54a85097c3f04819bdcb2125bfe3d2fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":10,
                  "y":630},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u19.png"}},
{
          "id":"844c0e39867d4479b709fb3a1492d73b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":660},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c5153bbe80f4872882a508f06855afa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":660},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fada28b49994474da506eb35e5dd9c56":{
      "packageId":"fada28b49994474da506eb35e5dd9c56",
      "type":"Axure:Master",
      "name":"底板（子页面）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a9f3c03e12c14394b49605490f5380f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":320,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ad1cc80c89a41acb906c231c2c6d55d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":320,
                    "height":15},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u11.png"}},
{
            "id":"5cbfd378f7fd49ae8ae8978e0b82dfe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8facad6e6d6d41ae94a2911bd72e2a82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u13.png"}},
{
            "id":"8e4635a390004c6f9d4539508bb6597c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c86faa2ccad4c689fee1a5797cdca32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u15.png"}},
{
            "id":"68932766f7d6416fb1efa9fda7953413",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":-7,
                "y":10},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eca5c557fc884ac0b9c52ed5bc5bd886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":-7,
                    "y":10},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/01-2__/u9.png"}}]}},
    "a2d1524f0a4d4be482cb8aeae8d7497e":{
      "packageId":"a2d1524f0a4d4be482cb8aeae8d7497e",
      "type":"Axure:Master",
      "name":"确认订单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a61df0b8fcbb417caad83c9947e127a8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":5,
                "y":0},
              "size":{
                "width":300,
                "height":106},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e49ced5c6f142699f2a115f9481fe1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":5,
                    "y":0},
                  "size":{
                    "width":300,
                    "height":106},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/01-2在线处理/u12.png",
              "normal~":"images/01-2在线处理/u12.png",
              "normal~":"images/01-2在线处理/u12.png"}},
{
            "id":"abad9496adb14e88b54f95e7d9baa1e9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":30,
                "y":83},
              "size":{
                "width":70,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ac38caf71e747cc8277346b06318076",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":30,
                    "y":83},
                  "size":{
                    "width":70,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"adcfb0f4eee34e9d8ee7d4e07ac7d8ab",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":70,
                "y":83},
              "size":{
                "width":70,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d4849fbdefac4540844e7a1bc16b8b41",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":70,
                    "y":83},
                  "size":{
                    "width":70,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"039aead57c8b4d3cb10264c193af6c45",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "location":{
                "x":100,
                "y":31},
              "size":{
                "width":200,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4d3f65fcc1b14742a4ebfef119f8e133",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":100,
                    "y":31},
                  "size":{
                    "width":200,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ccc9b0348b7a4bd98a9f4e2d2c9c0d33",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "location":{
                "x":30,
                "y":31},
              "size":{
                "width":50,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a729706f515b49f588b3f5cf9ed2f29d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":30,
                    "y":31},
                  "size":{
                    "width":50,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a3da960637fb4a38b9554f1d104c5131",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"12px",
              "fontWeight":"700",
              "location":{
                "x":30,
                "y":4},
              "size":{
                "width":80,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd83a11e78d74be0ab35fbda9bb795a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "location":{
                    "x":30,
                    "y":4},
                  "size":{
                    "width":80,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"167506c05e674bdd827ac9aa16d50a7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"12px",
              "fontWeight":"700",
              "location":{
                "x":100,
                "y":4},
              "size":{
                "width":80,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ac8506fbc7c41a4b8797cdfafad7fbc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "location":{
                    "x":100,
                    "y":4},
                  "size":{
                    "width":80,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7416c2e868df44f083c19c210056cdb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"12px",
              "fontWeight":"700",
              "location":{
                "x":180,
                "y":4},
              "size":{
                "width":80,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ebc709392e914c539721beb02123a833",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "location":{
                    "x":180,
                    "y":4},
                  "size":{
                    "width":80,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b5ac91e563234700bf23d66b14239261",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "location":{
                "x":100,
                "y":54},
              "size":{
                "width":200,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"846ca2aa32794ebc88a9fd993c3f914d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":100,
                    "y":54},
                  "size":{
                    "width":200,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"89eee6d39ed14b43a26e9a51df87e90c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "location":{
                "x":30,
                "y":54},
              "size":{
                "width":50,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f0231135df0541bea3e023f3b1f600cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":30,
                    "y":54},
                  "size":{
                    "width":50,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bfccb5acf89e47e98b902b18fb7070a1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":130,
                "y":83},
              "size":{
                "width":70,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18f849f2a0ac4e208a58aa2b18f5bfe3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":130,
                    "y":83},
                  "size":{
                    "width":70,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2da3ab0395bf49c3b2f7403593da0965",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":170,
                "y":83},
              "size":{
                "width":70,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cbc4bca8a9e2420f963ddcac068cb199",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":170,
                    "y":83},
                  "size":{
                    "width":70,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "3c07271c6a0c4389a4ccb003f7f42a5d":{
      "scriptId":"u0",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u1"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u2"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u3"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u4"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u5"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u6"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u7"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u8"}},
    "0afef41b9242452d84e9f2cb468dda22":{
      "scriptId":"u9"},
    "f805f80fbfd848a58df23a54d145f796":{
      "scriptId":"u10"},
    "db5068096e274fd4b133b5abf1c4014a":{
      "scriptId":"u11"},
    "8a61d516685a49f8b946cfaaa2dc86c4":{
      "scriptId":"u12"},
    "12122c7b65144865abfb252699103cb4":{
      "scriptId":"u13"},
    "d05a1846b834464185a4a0948d8e86ed":{
      "scriptId":"u14"},
    "d79c19344dac46f3a4887e4c51f8477c":{
      "scriptId":"u15"},
    "bcb88a93feae4fd1a973d9fa5a5da37e":{
      "scriptId":"u16"},
    "545b9f0fbe7c407bbb458b939f7df490":{
      "scriptId":"u17"},
    "1cc246445fdd4982bea85ecaae38b032":{
      "scriptId":"u18"},
    "77b6057b206b4893b4712c7aa7d3f5da":{
      "scriptId":"u19",
      "a61df0b8fcbb417caad83c9947e127a8":{
        "scriptId":"u20"},
      "0e49ced5c6f142699f2a115f9481fe1a":{
        "scriptId":"u21"},
      "abad9496adb14e88b54f95e7d9baa1e9":{
        "scriptId":"u22"},
      "1ac38caf71e747cc8277346b06318076":{
        "scriptId":"u23"},
      "adcfb0f4eee34e9d8ee7d4e07ac7d8ab":{
        "scriptId":"u24"},
      "d4849fbdefac4540844e7a1bc16b8b41":{
        "scriptId":"u25"},
      "039aead57c8b4d3cb10264c193af6c45":{
        "scriptId":"u26"},
      "4d3f65fcc1b14742a4ebfef119f8e133":{
        "scriptId":"u27"},
      "ccc9b0348b7a4bd98a9f4e2d2c9c0d33":{
        "scriptId":"u28"},
      "a729706f515b49f588b3f5cf9ed2f29d":{
        "scriptId":"u29"},
      "a3da960637fb4a38b9554f1d104c5131":{
        "scriptId":"u30"},
      "cd83a11e78d74be0ab35fbda9bb795a4":{
        "scriptId":"u31"},
      "167506c05e674bdd827ac9aa16d50a7a":{
        "scriptId":"u32"},
      "8ac8506fbc7c41a4b8797cdfafad7fbc":{
        "scriptId":"u33"},
      "7416c2e868df44f083c19c210056cdb0":{
        "scriptId":"u34"},
      "ebc709392e914c539721beb02123a833":{
        "scriptId":"u35"},
      "b5ac91e563234700bf23d66b14239261":{
        "scriptId":"u36"},
      "846ca2aa32794ebc88a9fd993c3f914d":{
        "scriptId":"u37"},
      "89eee6d39ed14b43a26e9a51df87e90c":{
        "scriptId":"u38"},
      "f0231135df0541bea3e023f3b1f600cb":{
        "scriptId":"u39"},
      "bfccb5acf89e47e98b902b18fb7070a1":{
        "scriptId":"u40"},
      "18f849f2a0ac4e208a58aa2b18f5bfe3":{
        "scriptId":"u41"},
      "2da3ab0395bf49c3b2f7403593da0965":{
        "scriptId":"u42"},
      "cbc4bca8a9e2420f963ddcac068cb199":{
        "scriptId":"u43"}},
    "bc78dd7ef47f4ff98ca333ea211d4807":{
      "scriptId":"u44",
      "a61df0b8fcbb417caad83c9947e127a8":{
        "scriptId":"u45"},
      "0e49ced5c6f142699f2a115f9481fe1a":{
        "scriptId":"u46"},
      "abad9496adb14e88b54f95e7d9baa1e9":{
        "scriptId":"u47"},
      "1ac38caf71e747cc8277346b06318076":{
        "scriptId":"u48"},
      "adcfb0f4eee34e9d8ee7d4e07ac7d8ab":{
        "scriptId":"u49"},
      "d4849fbdefac4540844e7a1bc16b8b41":{
        "scriptId":"u50"},
      "039aead57c8b4d3cb10264c193af6c45":{
        "scriptId":"u51"},
      "4d3f65fcc1b14742a4ebfef119f8e133":{
        "scriptId":"u52"},
      "ccc9b0348b7a4bd98a9f4e2d2c9c0d33":{
        "scriptId":"u53"},
      "a729706f515b49f588b3f5cf9ed2f29d":{
        "scriptId":"u54"},
      "a3da960637fb4a38b9554f1d104c5131":{
        "scriptId":"u55"},
      "cd83a11e78d74be0ab35fbda9bb795a4":{
        "scriptId":"u56"},
      "167506c05e674bdd827ac9aa16d50a7a":{
        "scriptId":"u57"},
      "8ac8506fbc7c41a4b8797cdfafad7fbc":{
        "scriptId":"u58"},
      "7416c2e868df44f083c19c210056cdb0":{
        "scriptId":"u59"},
      "ebc709392e914c539721beb02123a833":{
        "scriptId":"u60"},
      "b5ac91e563234700bf23d66b14239261":{
        "scriptId":"u61"},
      "846ca2aa32794ebc88a9fd993c3f914d":{
        "scriptId":"u62"},
      "89eee6d39ed14b43a26e9a51df87e90c":{
        "scriptId":"u63"},
      "f0231135df0541bea3e023f3b1f600cb":{
        "scriptId":"u64"},
      "bfccb5acf89e47e98b902b18fb7070a1":{
        "scriptId":"u65"},
      "18f849f2a0ac4e208a58aa2b18f5bfe3":{
        "scriptId":"u66"},
      "2da3ab0395bf49c3b2f7403593da0965":{
        "scriptId":"u67"},
      "cbc4bca8a9e2420f963ddcac068cb199":{
        "scriptId":"u68"}},
    "f0e6c40e750a41d897e5abdbfa9ca317":{
      "scriptId":"u69",
      "a61df0b8fcbb417caad83c9947e127a8":{
        "scriptId":"u70"},
      "0e49ced5c6f142699f2a115f9481fe1a":{
        "scriptId":"u71"},
      "abad9496adb14e88b54f95e7d9baa1e9":{
        "scriptId":"u72"},
      "1ac38caf71e747cc8277346b06318076":{
        "scriptId":"u73"},
      "adcfb0f4eee34e9d8ee7d4e07ac7d8ab":{
        "scriptId":"u74"},
      "d4849fbdefac4540844e7a1bc16b8b41":{
        "scriptId":"u75"},
      "039aead57c8b4d3cb10264c193af6c45":{
        "scriptId":"u76"},
      "4d3f65fcc1b14742a4ebfef119f8e133":{
        "scriptId":"u77"},
      "ccc9b0348b7a4bd98a9f4e2d2c9c0d33":{
        "scriptId":"u78"},
      "a729706f515b49f588b3f5cf9ed2f29d":{
        "scriptId":"u79"},
      "a3da960637fb4a38b9554f1d104c5131":{
        "scriptId":"u80"},
      "cd83a11e78d74be0ab35fbda9bb795a4":{
        "scriptId":"u81"},
      "167506c05e674bdd827ac9aa16d50a7a":{
        "scriptId":"u82"},
      "8ac8506fbc7c41a4b8797cdfafad7fbc":{
        "scriptId":"u83"},
      "7416c2e868df44f083c19c210056cdb0":{
        "scriptId":"u84"},
      "ebc709392e914c539721beb02123a833":{
        "scriptId":"u85"},
      "b5ac91e563234700bf23d66b14239261":{
        "scriptId":"u86"},
      "846ca2aa32794ebc88a9fd993c3f914d":{
        "scriptId":"u87"},
      "89eee6d39ed14b43a26e9a51df87e90c":{
        "scriptId":"u88"},
      "f0231135df0541bea3e023f3b1f600cb":{
        "scriptId":"u89"},
      "bfccb5acf89e47e98b902b18fb7070a1":{
        "scriptId":"u90"},
      "18f849f2a0ac4e208a58aa2b18f5bfe3":{
        "scriptId":"u91"},
      "2da3ab0395bf49c3b2f7403593da0965":{
        "scriptId":"u92"},
      "cbc4bca8a9e2420f963ddcac068cb199":{
        "scriptId":"u93"}},
    "34b68e108bbd41f3b3590afcfd05eaea":{
      "scriptId":"u94"},
    "70ca83c73a3c42faa81d1b192668075f":{
      "scriptId":"u95"},
    "cd9f6beebc7b45aa93d201f5b2faf7f9":{
      "scriptId":"u96"},
    "072b77e3371e4003a01465f8aae31071":{
      "scriptId":"u97"},
    "42f8e0a6a9a140f8b778fc12b41ffc33":{
      "scriptId":"u98"},
    "ee4b72cfe01f44c588eee1ff94cce7fb":{
      "scriptId":"u99"},
    "f9bc0152ad654715a7c81b3bdf2938d6":{
      "scriptId":"u100"},
    "b10af99dc44f44a0b7e75cbb1a6f9020":{
      "scriptId":"u101"},
    "5642c679edb64c7f8a340fac02ed07dc":{
      "scriptId":"u102"},
    "ddc41c026e404941b182db54ca8909aa":{
      "scriptId":"u103"},
    "19a3058d051e4345bc13ae7f36b91b19":{
      "scriptId":"u104"},
    "452727b8b0714be3b02bdb7a0a676593":{
      "scriptId":"u105"},
    "54a85097c3f04819bdcb2125bfe3d2fc":{
      "scriptId":"u106"},
    "844c0e39867d4479b709fb3a1492d73b":{
      "scriptId":"u107"},
    "6c5153bbe80f4872882a508f06855afa":{
      "scriptId":"u108"}}});