$axure.loadCurrentPage({
  "url":"15-3通知详情.html",
  "generationDate":new Date(1467963170675.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"050e44e99e8a4a94a2459d1e59951823",
    "type":"Axure:Page",
    "name":"15-3通知详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a74860baae9744d49756096e1231f055",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-7,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"feb7fffb14cf432b82caba9deb50e473",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":15},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a45048d7b18a45d39d50bf2f6c3fffa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":15},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14681a5bd18546c0b5a35f98e09b09c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":300,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c6c907b1cec4031ad10ff90ff1f4388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":300,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2933193612294dd3aa2633864feee9ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":77},
            "size":{
              "width":300,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e20f1bbc5e0406eb8a2b270f3df0927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":77},
                "size":{
                  "width":300,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61acb1ee1afc47feba9446c380f69e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":10,
              "y":104},
            "size":{
              "width":300,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"213a8c77258b435e9073ef3f0fcfae04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":10,
                  "y":104},
                "size":{
                  "width":300,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa9eaed7ddb04a33b75025e6ca550885",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":600},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcb39712b6e747b3a692753b617e9562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":600},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"05771619b7104803876eba911d6de3b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":10,
              "y":620},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9858ac1e7294d28bc9105e384ead33a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":10,
                  "y":620},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u19.png"}},
{
          "id":"fdf449a524b04d2485d90f16c9908dc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":663},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad21e58eecd449f3adc4468df035a38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":663},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fada28b49994474da506eb35e5dd9c56":{
      "packageId":"fada28b49994474da506eb35e5dd9c56",
      "type":"Axure:Master",
      "name":"底板（子页面）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a9f3c03e12c14394b49605490f5380f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":320,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ad1cc80c89a41acb906c231c2c6d55d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":320,
                    "height":15},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u11.png"}},
{
            "id":"5cbfd378f7fd49ae8ae8978e0b82dfe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8facad6e6d6d41ae94a2911bd72e2a82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u13.png"}},
{
            "id":"8e4635a390004c6f9d4539508bb6597c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c86faa2ccad4c689fee1a5797cdca32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u15.png"}},
{
            "id":"68932766f7d6416fb1efa9fda7953413",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":-7,
                "y":10},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eca5c557fc884ac0b9c52ed5bc5bd886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":-7,
                    "y":10},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/01-2__/u9.png"}}]}}},
  "objectPaths":{
    "a74860baae9744d49756096e1231f055":{
      "scriptId":"u0",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u1"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u2"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u3"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u4"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u5"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u6"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u7"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u8"}},
    "feb7fffb14cf432b82caba9deb50e473":{
      "scriptId":"u9"},
    "a45048d7b18a45d39d50bf2f6c3fffa9":{
      "scriptId":"u10"},
    "14681a5bd18546c0b5a35f98e09b09c9":{
      "scriptId":"u11"},
    "1c6c907b1cec4031ad10ff90ff1f4388":{
      "scriptId":"u12"},
    "2933193612294dd3aa2633864feee9ae":{
      "scriptId":"u13"},
    "4e20f1bbc5e0406eb8a2b270f3df0927":{
      "scriptId":"u14"},
    "61acb1ee1afc47feba9446c380f69e37":{
      "scriptId":"u15"},
    "213a8c77258b435e9073ef3f0fcfae04":{
      "scriptId":"u16"},
    "aa9eaed7ddb04a33b75025e6ca550885":{
      "scriptId":"u17"},
    "bcb39712b6e747b3a692753b617e9562":{
      "scriptId":"u18"},
    "05771619b7104803876eba911d6de3b5":{
      "scriptId":"u19"},
    "a9858ac1e7294d28bc9105e384ead33a":{
      "scriptId":"u20"},
    "fdf449a524b04d2485d90f16c9908dc8":{
      "scriptId":"u21"},
    "ad21e58eecd449f3adc4468df035a38f":{
      "scriptId":"u22"}}});