$axure.loadCurrentPage({
  "url":"02-2_3关于与子页面.html",
  "generationDate":new Date(1467963171351.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"94d543fa5bb443a28eca5770ebd7ca68",
    "type":"Axure:Page",
    "name":"02-2/3关于与子页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3f3086efb97149389c4e891ca0cf3e42",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-7,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"55d6c7d33d294fccae83e26aeb8d66ba",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":600},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aea3b8281f44253bddaeb0bf56ab32f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":600},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"7ae219104e3141ddace81c097089e522",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":16},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e231fb8c684a32aa2f97bcf1330590",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":16},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b7b24ed59b84df680cbe3dcfb654c9d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-7,
              "y":650}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"638d0f6b2cc643ab82228161cbc19eda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":666},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"838e9bde9b534d91930b0fd4344e8eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":666},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee8790af7f814d69b689ad8aa648ed0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":710},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ada5a057442840138d782fc45a0f9ce0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":710},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a023aecdf5fc48e3b06e43ec2ccfa3af",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":737},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}},
{
          "id":"8eb3485106094bf3b3dbae6ddef5f27f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":757},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23d7eb99d73a45a08339cdaddc27013f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":757},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce4f44a57a4f44b09e51f74070e3f265",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":784},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}},
{
          "id":"31e3977496e543f8a3bc388234faecc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":804},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b237c50f81e8425fafd801ba130e15e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":804},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfa8113d4bca4bb48dfa123c017d5384",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":831},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}},
{
          "id":"566a77e9de5b4fca96e6160e3463959b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":853},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee58234cf24b4eccbbb39bbc6696e30c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":853},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"644ba7cac53c4339832331c19f036e34",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":880},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}},
{
          "id":"c98247d7b7fa4962ab3277828d644ba9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":650}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"d99d0b53a47a4ffb890d8b4fb927ce57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":470,
              "y":666},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"987e8a94014f4d54a2389809e1ee29bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":470,
                  "y":666},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae06f3931a7348c5819d3f77fcb81afe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":410,
              "y":710},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89fc0e5aa98d46349afcef79cbae32e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":410,
                  "y":710},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0e8bd6292184ce9abaf6214ef2af458",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":793,
              "y":650}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"3608edc6690f44eb907f7e08c02895ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":870,
              "y":666},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5997524f46a647bb971f73c6ef4c7d38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":870,
                  "y":666},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dc3b81ee8474d4ea3c9a660c525b7dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":810,
              "y":710},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eca605561df4721ad81807e33a6de53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":810,
                  "y":710},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad620c3216424f54832a725c4cc0c982",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1193,
              "y":650}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"2d69b339ac8d432a97b6f421439eec0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":1270,
              "y":666},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e19c5928944d979e5a88c8a6f24543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":1270,
                  "y":666},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b9b5442435e463bbb51748354655f91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":1210,
              "y":710},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31cd38d039384e63a9bdf19c3d84b966",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":1210,
                  "y":710},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18c43cbf968849f9ade7d285c4f7422b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45f5bc3f6c114739ab0464fd56159bdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ea8d577975343eb9894905e446c43a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":86},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}},
{
          "id":"323dc3f61b374be480b17c9ad51463cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":106},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf5440392ba4dc49d251a19f5672a6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":106},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bc52910dd4e4aa9a64702624030c958",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":134},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}},
{
          "id":"6116f27da430419c90854f68af56d18b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":154},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31065f7bb0924ff593916ca864ae8043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":154},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07523ffbf9f743c7bf28bd9106f2b73d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":180},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}},
{
          "id":"26356e866f1345c8b5c9c2c911c0ead9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":202},
            "size":{
              "width":300,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565b2c887a7d41f9b5d562b6ae3013b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":202},
                "size":{
                  "width":300,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fa78b871b4d4da8824171cc2ddbe08d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":230},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/04-3罚单处理/u68_line.png"}}]}},
  "masters":{
    "fada28b49994474da506eb35e5dd9c56":{
      "packageId":"fada28b49994474da506eb35e5dd9c56",
      "type":"Axure:Master",
      "name":"底板（子页面）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a9f3c03e12c14394b49605490f5380f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":320,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ad1cc80c89a41acb906c231c2c6d55d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":320,
                    "height":15},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u11.png",
              "normal~":"images/全局说明/u11.png",
              "normal~":"images/全局说明/u11.png",
              "normal~":"images/全局说明/u11.png",
              "normal~":"images/全局说明/u11.png"}},
{
            "id":"5cbfd378f7fd49ae8ae8978e0b82dfe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8facad6e6d6d41ae94a2911bd72e2a82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u13.png",
              "normal~":"images/全局说明/u13.png",
              "normal~":"images/全局说明/u13.png",
              "normal~":"images/全局说明/u13.png",
              "normal~":"images/全局说明/u13.png"}},
{
            "id":"8e4635a390004c6f9d4539508bb6597c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c86faa2ccad4c689fee1a5797cdca32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u15.png",
              "normal~":"images/全局说明/u15.png",
              "normal~":"images/全局说明/u15.png",
              "normal~":"images/全局说明/u15.png",
              "normal~":"images/全局说明/u15.png"}},
{
            "id":"68932766f7d6416fb1efa9fda7953413",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":-7,
                "y":10},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eca5c557fc884ac0b9c52ed5bc5bd886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":-7,
                    "y":10},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/01-2__/u9.png",
              "normal~":"images/01-2__/u9.png",
              "normal~":"images/01-2__/u9.png",
              "normal~":"images/01-2__/u9.png",
              "normal~":"images/01-2__/u9.png"}}]}}},
  "objectPaths":{
    "3f3086efb97149389c4e891ca0cf3e42":{
      "scriptId":"u0",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u1"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u2"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u3"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u4"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u5"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u6"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u7"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u8"}},
    "55d6c7d33d294fccae83e26aeb8d66ba":{
      "scriptId":"u9"},
    "6aea3b8281f44253bddaeb0bf56ab32f":{
      "scriptId":"u10"},
    "7ae219104e3141ddace81c097089e522":{
      "scriptId":"u11"},
    "75e231fb8c684a32aa2f97bcf1330590":{
      "scriptId":"u12"},
    "7b7b24ed59b84df680cbe3dcfb654c9d":{
      "scriptId":"u13",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u14"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u15"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u16"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u17"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u18"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u19"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u20"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u21"}},
    "638d0f6b2cc643ab82228161cbc19eda":{
      "scriptId":"u22"},
    "838e9bde9b534d91930b0fd4344e8eda":{
      "scriptId":"u23"},
    "ee8790af7f814d69b689ad8aa648ed0b":{
      "scriptId":"u24"},
    "ada5a057442840138d782fc45a0f9ce0":{
      "scriptId":"u25"},
    "a023aecdf5fc48e3b06e43ec2ccfa3af":{
      "scriptId":"u26"},
    "8eb3485106094bf3b3dbae6ddef5f27f":{
      "scriptId":"u27"},
    "23d7eb99d73a45a08339cdaddc27013f":{
      "scriptId":"u28"},
    "ce4f44a57a4f44b09e51f74070e3f265":{
      "scriptId":"u29"},
    "31e3977496e543f8a3bc388234faecc9":{
      "scriptId":"u30"},
    "b237c50f81e8425fafd801ba130e15e8":{
      "scriptId":"u31"},
    "bfa8113d4bca4bb48dfa123c017d5384":{
      "scriptId":"u32"},
    "566a77e9de5b4fca96e6160e3463959b":{
      "scriptId":"u33"},
    "ee58234cf24b4eccbbb39bbc6696e30c":{
      "scriptId":"u34"},
    "644ba7cac53c4339832331c19f036e34":{
      "scriptId":"u35"},
    "c98247d7b7fa4962ab3277828d644ba9":{
      "scriptId":"u36",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u37"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u38"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u39"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u40"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u41"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u42"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u43"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u44"}},
    "d99d0b53a47a4ffb890d8b4fb927ce57":{
      "scriptId":"u45"},
    "987e8a94014f4d54a2389809e1ee29bf":{
      "scriptId":"u46"},
    "ae06f3931a7348c5819d3f77fcb81afe":{
      "scriptId":"u47"},
    "89fc0e5aa98d46349afcef79cbae32e5":{
      "scriptId":"u48"},
    "c0e8bd6292184ce9abaf6214ef2af458":{
      "scriptId":"u49",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u50"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u51"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u52"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u53"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u54"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u55"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u56"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u57"}},
    "3608edc6690f44eb907f7e08c02895ee":{
      "scriptId":"u58"},
    "5997524f46a647bb971f73c6ef4c7d38":{
      "scriptId":"u59"},
    "3dc3b81ee8474d4ea3c9a660c525b7dc":{
      "scriptId":"u60"},
    "0eca605561df4721ad81807e33a6de53":{
      "scriptId":"u61"},
    "ad620c3216424f54832a725c4cc0c982":{
      "scriptId":"u62",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u63"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u64"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u65"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u66"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u67"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u68"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u69"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u70"}},
    "2d69b339ac8d432a97b6f421439eec0b":{
      "scriptId":"u71"},
    "a9e19c5928944d979e5a88c8a6f24543":{
      "scriptId":"u72"},
    "3b9b5442435e463bbb51748354655f91":{
      "scriptId":"u73"},
    "31cd38d039384e63a9bdf19c3d84b966":{
      "scriptId":"u74"},
    "18c43cbf968849f9ade7d285c4f7422b":{
      "scriptId":"u75"},
    "45f5bc3f6c114739ab0464fd56159bdc":{
      "scriptId":"u76"},
    "3ea8d577975343eb9894905e446c43a2":{
      "scriptId":"u77"},
    "323dc3f61b374be480b17c9ad51463cf":{
      "scriptId":"u78"},
    "bbf5440392ba4dc49d251a19f5672a6f":{
      "scriptId":"u79"},
    "8bc52910dd4e4aa9a64702624030c958":{
      "scriptId":"u80"},
    "6116f27da430419c90854f68af56d18b":{
      "scriptId":"u81"},
    "31065f7bb0924ff593916ca864ae8043":{
      "scriptId":"u82"},
    "07523ffbf9f743c7bf28bd9106f2b73d":{
      "scriptId":"u83"},
    "26356e866f1345c8b5c9c2c911c0ead9":{
      "scriptId":"u84"},
    "565b2c887a7d41f9b5d562b6ae3013b0":{
      "scriptId":"u85"},
    "3fa78b871b4d4da8824171cc2ddbe08d":{
      "scriptId":"u86"}}});