$axure.loadCurrentPage({
  "url":"02-2选择驾驶证.html",
  "generationDate":new Date(1467963162281.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"14501e1532a24b6c8bfe4eaeba7cedc0",
    "type":"Axure:Page",
    "name":"02-2选择驾驶证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b0df0e1884ff4a2883e2c7643cfd4dbd",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-7,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"b09698f5543e447eba49135b18769cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":15},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc398e1f21d549ee8d34b7b3aef2e60e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":15},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffb7e58ec0d641a69843e670cfa709a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":10,
              "y":450},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5ea61a5c9224f4988a429386bf4fe3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":10,
                  "y":450},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 04-2确认订单(在线处理)",
                      "target":{
                        "targetType":"page",
                        "url":"04-2确认订单_在线处理_.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/02-0第一次进入/u25.png"}},
{
          "id":"801f60c73f5a4d23a89205a9b98ea8f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"right",
            "location":{
              "x":255,
              "y":16},
            "size":{
              "width":55,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3298296a471d4929bb71de2bce0db693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"right",
                "location":{
                  "x":255,
                  "y":16},
                "size":{
                  "width":55,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 03-2添加/修改扣分驾驶证（在线处理）",
                      "target":{
                        "targetType":"page",
                        "url":"03-2添加_修改扣分驾驶证（在线处理）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75565800346c493e8dce5628a3923ba0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":600},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf2a6017969f41749a448a749bc274ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":600},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"a6e3aca9c09e4365832c513eb13764a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":10,
              "y":630},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbab19487b474a099b6dff31b6369135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":10,
                  "y":630},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u19.png"}},
{
          "id":"b9c8ccd9d6bf497aa3ad2c077a07c2a3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":680}},
          "adaptiveStyles":{
},
          "masterId":"fada28b49994474da506eb35e5dd9c56"},
{
          "id":"eef99d22779f4043bbfaf0f8e3441163",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":695},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cbcce8865644dd1beb4f25fe77879c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":81,
                  "y":695},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4081fe7543f44be18ac4c41710a5bdd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":21,
              "y":1130},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"370c979717d94edc939707e37ef44f76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":21,
                  "y":1130},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 04-2确认订单(在线处理)",
                      "target":{
                        "targetType":"page",
                        "url":"04-2确认订单_在线处理_.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/02-0第一次进入/u25.png"}},
{
          "id":"d62f64058b544c36ac967d717ba3f253",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"right",
            "location":{
              "x":265,
              "y":696},
            "size":{
              "width":55,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac1f818c249b4c1693e6ba782a4d69e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"right",
                "location":{
                  "x":265,
                  "y":696},
                "size":{
                  "width":55,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 03-2添加/修改扣分驾驶证（在线处理）",
                      "target":{
                        "targetType":"page",
                        "url":"03-2添加_修改扣分驾驶证（在线处理）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f566cb48951744f9bee7e9db84a151bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":420,
              "y":793},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c40dd15f03e4e8d90ec3cee48bafcc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":420,
                  "y":793},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb4b9484cfae467aa1e5f91338c7eeab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":420,
              "y":880},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f86c7867a384e4c91c3c1bf1a85682a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":880},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21497cfb3cd44c72930966ac366a55cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":480,
              "y":880},
            "size":{
              "width":270,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e37d9a4e2efd40d182795e05215708bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":480,
                  "y":880},
                "size":{
                  "width":270,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dafc22ccbfe4c37be93b02991cf06ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":420,
              "y":1170},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b8df6f6e9e547eab0aa70b0f61bc56c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":420,
                  "y":1170},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c61896c9f4f44c28cc782d61d64a649",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":420,
              "y":1200},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c89f4903e1e845378503a2d4b9070d56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":1200},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed1e1f1aad074dbd89efe42bc0f4e8a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":490,
              "y":1200},
            "size":{
              "width":270,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54cae01a06ef49c69eb3805f37fbfe07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":490,
                  "y":1200},
                "size":{
                  "width":270,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b9920f8fa504369a26cbe708b7fe666",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":498,
              "y":1172},
            "size":{
              "width":13,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cd8d0e19ba74ca4bd46d3158399b058",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":498,
                  "y":1172},
                "size":{
                  "width":13,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-1违章处理首页/u265.png"}},
{
          "id":"e74930845ec4475d9e9fc8809a727f56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":420,
              "y":694},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c492c82ec245d5813dd30eefbb7a02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":420,
                  "y":694},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47b3fa47f4ef417ebe836da9ed2064b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":420,
              "y":853},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df79653381374290932ad6cfc2ade991",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":853},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0ae355357dd4c75b10efa1287418378",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":550,
              "y":853},
            "size":{
              "width":270,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f96003d869524e64a4f4d992f665126b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":550,
                  "y":853},
                "size":{
                  "width":270,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5166b7a45c7d439981fc4ed44b32fa68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":800,
              "y":620},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"575e9ce860aa4b4790e43d2e81d0ca3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":800,
                  "y":620},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01-2__/u19.png"}},
{
          "id":"ceb13ad4e3dc4da8bc5b6a694e0b8beb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":725}},
          "adaptiveStyles":{
},
          "masterId":"db5919473ae747a29cfaf0b265eeb05f"},
{
          "id":"af43bf2fb98d421daead56fe042764df",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":765}},
          "adaptiveStyles":{
},
          "masterId":"db5919473ae747a29cfaf0b265eeb05f"},
{
          "id":"1d8fc738f9814436aa1210b7bfd8a888",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":45}},
          "adaptiveStyles":{
},
          "masterId":"db5919473ae747a29cfaf0b265eeb05f"},
{
          "id":"85934fce906e4a1d95625fa18bd67d04",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":85}},
          "adaptiveStyles":{
},
          "masterId":"db5919473ae747a29cfaf0b265eeb05f"},
{
          "id":"842a01e86c584d82918bd986ab3938c1",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":52},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84dc368f8e0a48979ff90f1f6f4c9b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":52},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4459f483a46d49858b5eb495d341eb8f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":92},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb8e61e03114269944986940b436dad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":92},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0f3ac10f66d34264affc1db4ea92e8eb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":732},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd024f3296b247be8ac07e7f2ef0f662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":732},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"15166b7fe951464c993a2cfb8334123a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":772},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a46eb4de16c54f4792f0c8f8d370daab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":772},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a1d77288f3524783855e699e85f60ba4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":420,
              "y":730},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"813392e650ea488fabb6959e3296aafe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":730},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57b8b049c33441428e9a3444e251ad16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":480,
              "y":730},
            "size":{
              "width":270,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28af990f69d64b008d18f781de696c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":480,
                  "y":730},
                "size":{
                  "width":270,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c648239f733f4147b5b5d0990b89746b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":420,
              "y":823},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc0ce7f1d6d491c939aa979e6b3ec33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":823},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93db0ce1f5db41639a00aa2917f1d735",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":480,
              "y":823},
            "size":{
              "width":180,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ab8c3d88ab248e4965078bdff2cccbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":480,
                  "y":823},
                "size":{
                  "width":180,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af5df5af0f474d80a1a421c998900b5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":420,
              "y":940},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb02910f5dc744eca6785d9393449610",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":420,
                  "y":940},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71cb6ebd36344cacbdf5491e1e52fcb1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":980}},
          "adaptiveStyles":{
},
          "masterId":"db5919473ae747a29cfaf0b265eeb05f"},
{
          "id":"7307e0bd20444e67b702e6656e0fcc72",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":987},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49c19830b54749dbafd97b618d554b87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":987},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"04ae2418e3844f9fb37f449f7df9d934",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":800,
              "y":1172},
            "size":{
              "width":320,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e54f7d7cc14a4e998061186a8d0ced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":800,
                  "y":1172},
                "size":{
                  "width":320,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-2选择驾驶证/u121.png"}},
{
          "id":"72b3e6df737540df9382e1bd64d787ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":810,
              "y":1185},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5459f731e2324a8ca14d13f743597bfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":810,
                  "y":1185},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1951a2cdcd95487880e527b30890a6d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":810,
              "y":1215},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ca6a71d2cf414da7170307da766a2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":810,
                  "y":1215},
                "size":{
                  "width":300,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfeba6696106472ab55427741deb2214",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":511,
              "y":1180},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fe3b7401f2c472885210370fe680d61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":511,
                  "y":1180},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"c9ef441d6fe44e19a2ce05f42db394cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":420,
              "y":1020},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c8eeb97eb174060ac73608f0cf19d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":1020},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6932b38374784e13871adeedfefcafd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":420,
              "y":1050},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6127ba991bb941e1a058da5d4c8e48f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":1050},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9b65b11a3ee4e9d9d31abdb3caa68b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":420,
              "y":1080},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c7c1141ce1444b8b89b8a6c84128dce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":1080},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f935f52ce0b34fe2a4feacd3707feb1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":420,
              "y":1110},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c13443fdcc9949558ec95e6d56e907d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":1110},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d030e9dda3049a79b8283d57b506e6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":490,
              "y":1230},
            "size":{
              "width":270,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4fe04cf71244925a3d5c5599fdc5d4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":490,
                  "y":1230},
                "size":{
                  "width":270,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "fada28b49994474da506eb35e5dd9c56":{
      "packageId":"fada28b49994474da506eb35e5dd9c56",
      "type":"Axure:Master",
      "name":"底板（子页面）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a9f3c03e12c14394b49605490f5380f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":320,
                "height":15},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ad1cc80c89a41acb906c231c2c6d55d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":320,
                    "height":15},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u11.png",
              "normal~":"images/全局说明/u11.png"}},
{
            "id":"5cbfd378f7fd49ae8ae8978e0b82dfe1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8facad6e6d6d41ae94a2911bd72e2a82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u13.png",
              "normal~":"images/全局说明/u13.png"}},
{
            "id":"8e4635a390004c6f9d4539508bb6597c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c86faa2ccad4c689fee1a5797cdca32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u15.png",
              "normal~":"images/全局说明/u15.png"}},
{
            "id":"68932766f7d6416fb1efa9fda7953413",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":-7,
                "y":10},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eca5c557fc884ac0b9c52ed5bc5bd886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":-7,
                    "y":10},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/01-2__/u9.png",
              "normal~":"images/01-2__/u9.png"}}]}},
    "db5919473ae747a29cfaf0b265eeb05f":{
      "packageId":"db5919473ae747a29cfaf0b265eeb05f",
      "type":"Axure:Master",
      "name":"选择驾驶证",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"eee352c4d65f4ca89017a36ecc7fbd90",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28b684585ea64ac0a9542ab0d35a34d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/02-2选择驾驶证/u57.png",
              "normal~":"images/02-2选择驾驶证/u57.png",
              "normal~":"images/02-2选择驾驶证/u57.png",
              "normal~":"images/02-2选择驾驶证/u57.png",
              "normal~":"images/02-2选择驾驶证/u57.png"}},
{
            "id":"ad6b486dd3e145aab24c1352c5914199",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"12px",
              "fontWeight":"700",
              "location":{
                "x":50,
                "y":6},
              "size":{
                "width":200,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9eb1ec70e924c78b66276fd3c70fa04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "location":{
                    "x":50,
                    "y":6},
                  "size":{
                    "width":200,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbd95609a93e44b6a85b5edd4ff8b1e6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "horizontalAlignment":"right",
              "location":{
                "x":110,
                "y":6},
              "size":{
                "width":160,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4b0a2958cc0c4b2094db2e33550950a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":110,
                    "y":6},
                  "size":{
                    "width":160,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"45a9b5ca63104cc3bc46e8e52d42d046",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "horizontalAlignment":"right",
              "location":{
                "x":270,
                "y":6},
              "size":{
                "width":40,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"572d37f110b042aabaf52e4984b50e11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":270,
                    "y":6},
                  "size":{
                    "width":40,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 03-2添加/修改扣分驾驶证（在线处理）",
                        "target":{
                          "targetType":"page",
                          "url":"03-2添加_修改扣分驾驶证（在线处理）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "b0df0e1884ff4a2883e2c7643cfd4dbd":{
      "scriptId":"u0",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u1"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u2"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u3"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u4"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u5"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u6"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u7"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u8"}},
    "b09698f5543e447eba49135b18769cc1":{
      "scriptId":"u9"},
    "cc398e1f21d549ee8d34b7b3aef2e60e":{
      "scriptId":"u10"},
    "ffb7e58ec0d641a69843e670cfa709a7":{
      "scriptId":"u11"},
    "c5ea61a5c9224f4988a429386bf4fe3a":{
      "scriptId":"u12"},
    "801f60c73f5a4d23a89205a9b98ea8f1":{
      "scriptId":"u13"},
    "3298296a471d4929bb71de2bce0db693":{
      "scriptId":"u14"},
    "75565800346c493e8dce5628a3923ba0":{
      "scriptId":"u15"},
    "bf2a6017969f41749a448a749bc274ee":{
      "scriptId":"u16"},
    "a6e3aca9c09e4365832c513eb13764a7":{
      "scriptId":"u17"},
    "cbab19487b474a099b6dff31b6369135":{
      "scriptId":"u18"},
    "b9c8ccd9d6bf497aa3ad2c077a07c2a3":{
      "scriptId":"u19",
      "a9f3c03e12c14394b49605490f5380f2":{
        "scriptId":"u20"},
      "3ad1cc80c89a41acb906c231c2c6d55d":{
        "scriptId":"u21"},
      "5cbfd378f7fd49ae8ae8978e0b82dfe1":{
        "scriptId":"u22"},
      "8facad6e6d6d41ae94a2911bd72e2a82":{
        "scriptId":"u23"},
      "8e4635a390004c6f9d4539508bb6597c":{
        "scriptId":"u24"},
      "6c86faa2ccad4c689fee1a5797cdca32":{
        "scriptId":"u25"},
      "68932766f7d6416fb1efa9fda7953413":{
        "scriptId":"u26"},
      "eca5c557fc884ac0b9c52ed5bc5bd886":{
        "scriptId":"u27"}},
    "eef99d22779f4043bbfaf0f8e3441163":{
      "scriptId":"u28"},
    "2cbcce8865644dd1beb4f25fe77879c2":{
      "scriptId":"u29"},
    "4081fe7543f44be18ac4c41710a5bdd9":{
      "scriptId":"u30"},
    "370c979717d94edc939707e37ef44f76":{
      "scriptId":"u31"},
    "d62f64058b544c36ac967d717ba3f253":{
      "scriptId":"u32"},
    "ac1f818c249b4c1693e6ba782a4d69e9":{
      "scriptId":"u33"},
    "f566cb48951744f9bee7e9db84a151bc":{
      "scriptId":"u34"},
    "2c40dd15f03e4e8d90ec3cee48bafcc3":{
      "scriptId":"u35"},
    "bb4b9484cfae467aa1e5f91338c7eeab":{
      "scriptId":"u36"},
    "6f86c7867a384e4c91c3c1bf1a85682a":{
      "scriptId":"u37"},
    "21497cfb3cd44c72930966ac366a55cf":{
      "scriptId":"u38"},
    "e37d9a4e2efd40d182795e05215708bf":{
      "scriptId":"u39"},
    "7dafc22ccbfe4c37be93b02991cf06ce":{
      "scriptId":"u40"},
    "7b8df6f6e9e547eab0aa70b0f61bc56c":{
      "scriptId":"u41"},
    "4c61896c9f4f44c28cc782d61d64a649":{
      "scriptId":"u42"},
    "c89f4903e1e845378503a2d4b9070d56":{
      "scriptId":"u43"},
    "ed1e1f1aad074dbd89efe42bc0f4e8a0":{
      "scriptId":"u44"},
    "54cae01a06ef49c69eb3805f37fbfe07":{
      "scriptId":"u45"},
    "3b9920f8fa504369a26cbe708b7fe666":{
      "scriptId":"u46"},
    "0cd8d0e19ba74ca4bd46d3158399b058":{
      "scriptId":"u47"},
    "e74930845ec4475d9e9fc8809a727f56":{
      "scriptId":"u48"},
    "d1c492c82ec245d5813dd30eefbb7a02":{
      "scriptId":"u49"},
    "47b3fa47f4ef417ebe836da9ed2064b7":{
      "scriptId":"u50"},
    "df79653381374290932ad6cfc2ade991":{
      "scriptId":"u51"},
    "a0ae355357dd4c75b10efa1287418378":{
      "scriptId":"u52"},
    "f96003d869524e64a4f4d992f665126b":{
      "scriptId":"u53"},
    "5166b7a45c7d439981fc4ed44b32fa68":{
      "scriptId":"u54"},
    "575e9ce860aa4b4790e43d2e81d0ca3a":{
      "scriptId":"u55"},
    "ceb13ad4e3dc4da8bc5b6a694e0b8beb":{
      "scriptId":"u56",
      "eee352c4d65f4ca89017a36ecc7fbd90":{
        "scriptId":"u57"},
      "28b684585ea64ac0a9542ab0d35a34d8":{
        "scriptId":"u58"},
      "ad6b486dd3e145aab24c1352c5914199":{
        "scriptId":"u59"},
      "b9eb1ec70e924c78b66276fd3c70fa04":{
        "scriptId":"u60"},
      "dbd95609a93e44b6a85b5edd4ff8b1e6":{
        "scriptId":"u61"},
      "4b0a2958cc0c4b2094db2e33550950a9":{
        "scriptId":"u62"},
      "45a9b5ca63104cc3bc46e8e52d42d046":{
        "scriptId":"u63"},
      "572d37f110b042aabaf52e4984b50e11":{
        "scriptId":"u64"}},
    "af43bf2fb98d421daead56fe042764df":{
      "scriptId":"u65",
      "eee352c4d65f4ca89017a36ecc7fbd90":{
        "scriptId":"u66"},
      "28b684585ea64ac0a9542ab0d35a34d8":{
        "scriptId":"u67"},
      "ad6b486dd3e145aab24c1352c5914199":{
        "scriptId":"u68"},
      "b9eb1ec70e924c78b66276fd3c70fa04":{
        "scriptId":"u69"},
      "dbd95609a93e44b6a85b5edd4ff8b1e6":{
        "scriptId":"u70"},
      "4b0a2958cc0c4b2094db2e33550950a9":{
        "scriptId":"u71"},
      "45a9b5ca63104cc3bc46e8e52d42d046":{
        "scriptId":"u72"},
      "572d37f110b042aabaf52e4984b50e11":{
        "scriptId":"u73"}},
    "1d8fc738f9814436aa1210b7bfd8a888":{
      "scriptId":"u74",
      "eee352c4d65f4ca89017a36ecc7fbd90":{
        "scriptId":"u75"},
      "28b684585ea64ac0a9542ab0d35a34d8":{
        "scriptId":"u76"},
      "ad6b486dd3e145aab24c1352c5914199":{
        "scriptId":"u77"},
      "b9eb1ec70e924c78b66276fd3c70fa04":{
        "scriptId":"u78"},
      "dbd95609a93e44b6a85b5edd4ff8b1e6":{
        "scriptId":"u79"},
      "4b0a2958cc0c4b2094db2e33550950a9":{
        "scriptId":"u80"},
      "45a9b5ca63104cc3bc46e8e52d42d046":{
        "scriptId":"u81"},
      "572d37f110b042aabaf52e4984b50e11":{
        "scriptId":"u82"}},
    "85934fce906e4a1d95625fa18bd67d04":{
      "scriptId":"u83",
      "eee352c4d65f4ca89017a36ecc7fbd90":{
        "scriptId":"u84"},
      "28b684585ea64ac0a9542ab0d35a34d8":{
        "scriptId":"u85"},
      "ad6b486dd3e145aab24c1352c5914199":{
        "scriptId":"u86"},
      "b9eb1ec70e924c78b66276fd3c70fa04":{
        "scriptId":"u87"},
      "dbd95609a93e44b6a85b5edd4ff8b1e6":{
        "scriptId":"u88"},
      "4b0a2958cc0c4b2094db2e33550950a9":{
        "scriptId":"u89"},
      "45a9b5ca63104cc3bc46e8e52d42d046":{
        "scriptId":"u90"},
      "572d37f110b042aabaf52e4984b50e11":{
        "scriptId":"u91"}},
    "842a01e86c584d82918bd986ab3938c1":{
      "scriptId":"u92"},
    "84dc368f8e0a48979ff90f1f6f4c9b36":{
      "scriptId":"u93"},
    "4459f483a46d49858b5eb495d341eb8f":{
      "scriptId":"u94"},
    "6fb8e61e03114269944986940b436dad":{
      "scriptId":"u95"},
    "0f3ac10f66d34264affc1db4ea92e8eb":{
      "scriptId":"u96"},
    "fd024f3296b247be8ac07e7f2ef0f662":{
      "scriptId":"u97"},
    "15166b7fe951464c993a2cfb8334123a":{
      "scriptId":"u98"},
    "a46eb4de16c54f4792f0c8f8d370daab":{
      "scriptId":"u99"},
    "a1d77288f3524783855e699e85f60ba4":{
      "scriptId":"u100"},
    "813392e650ea488fabb6959e3296aafe":{
      "scriptId":"u101"},
    "57b8b049c33441428e9a3444e251ad16":{
      "scriptId":"u102"},
    "28af990f69d64b008d18f781de696c63":{
      "scriptId":"u103"},
    "c648239f733f4147b5b5d0990b89746b":{
      "scriptId":"u104"},
    "4cc0ce7f1d6d491c939aa979e6b3ec33":{
      "scriptId":"u105"},
    "93db0ce1f5db41639a00aa2917f1d735":{
      "scriptId":"u106"},
    "7ab8c3d88ab248e4965078bdff2cccbd":{
      "scriptId":"u107"},
    "af5df5af0f474d80a1a421c998900b5f":{
      "scriptId":"u108"},
    "fb02910f5dc744eca6785d9393449610":{
      "scriptId":"u109"},
    "71cb6ebd36344cacbdf5491e1e52fcb1":{
      "scriptId":"u110",
      "eee352c4d65f4ca89017a36ecc7fbd90":{
        "scriptId":"u111"},
      "28b684585ea64ac0a9542ab0d35a34d8":{
        "scriptId":"u112"},
      "ad6b486dd3e145aab24c1352c5914199":{
        "scriptId":"u113"},
      "b9eb1ec70e924c78b66276fd3c70fa04":{
        "scriptId":"u114"},
      "dbd95609a93e44b6a85b5edd4ff8b1e6":{
        "scriptId":"u115"},
      "4b0a2958cc0c4b2094db2e33550950a9":{
        "scriptId":"u116"},
      "45a9b5ca63104cc3bc46e8e52d42d046":{
        "scriptId":"u117"},
      "572d37f110b042aabaf52e4984b50e11":{
        "scriptId":"u118"}},
    "7307e0bd20444e67b702e6656e0fcc72":{
      "scriptId":"u119"},
    "49c19830b54749dbafd97b618d554b87":{
      "scriptId":"u120"},
    "04ae2418e3844f9fb37f449f7df9d934":{
      "scriptId":"u121"},
    "93e54f7d7cc14a4e998061186a8d0ced":{
      "scriptId":"u122"},
    "72b3e6df737540df9382e1bd64d787ee":{
      "scriptId":"u123"},
    "5459f731e2324a8ca14d13f743597bfc":{
      "scriptId":"u124"},
    "1951a2cdcd95487880e527b30890a6d7":{
      "scriptId":"u125"},
    "76ca6a71d2cf414da7170307da766a2c":{
      "scriptId":"u126"},
    "bfeba6696106472ab55427741deb2214":{
      "scriptId":"u127"},
    "2fe3b7401f2c472885210370fe680d61":{
      "scriptId":"u128"},
    "c9ef441d6fe44e19a2ce05f42db394cf":{
      "scriptId":"u129"},
    "4c8eeb97eb174060ac73608f0cf19d3b":{
      "scriptId":"u130"},
    "6932b38374784e13871adeedfefcafd3":{
      "scriptId":"u131"},
    "6127ba991bb941e1a058da5d4c8e48f3":{
      "scriptId":"u132"},
    "e9b65b11a3ee4e9d9d31abdb3caa68b5":{
      "scriptId":"u133"},
    "3c7c1141ce1444b8b89b8a6c84128dce":{
      "scriptId":"u134"},
    "f935f52ce0b34fe2a4feacd3707feb1b":{
      "scriptId":"u135"},
    "c13443fdcc9949558ec95e6d56e907d2":{
      "scriptId":"u136"},
    "8d030e9dda3049a79b8283d57b506e6f":{
      "scriptId":"u137"},
    "c4fe04cf71244925a3d5c5599fdc5d4b":{
      "scriptId":"u138"}}});