$axure.loadCurrentPage({
  "url":"01-0启动页.html",
  "generationDate":new Date(1467963159595.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStYPosition",
"AxStYLimit",
"AxStRowHeight",
"AxStScaleFactor",
"AxStYRotateDirection"],
  "page":{
    "packageId":"5721438d5f3d488fa3360c316bf1a94c",
    "type":"Axure:Page",
    "name":"01-0启动页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7fb7cb0693664248a55121be38cfdf36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":320,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb3fbfcf759140ac909e43f50a35277b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":320,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u11.png"}},
{
          "id":"e1074868e5784de2b0be661dfd254774",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":10},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037b9a1ba8d74106b68bc6e3ffec3693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":10},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 03-1违章处理首页",
                      "target":{
                        "targetType":"page",
                        "url":"03-1违章处理首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/01-0启动页/u2.png"}},
{
          "id":"963b488b3f3d44c6b7fca0bd2640e65e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":89,
              "y":128},
            "size":{
              "width":142,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc67f58a104949b8b799e44b5032cf5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":128},
                "size":{
                  "width":142,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7fb7cb0693664248a55121be38cfdf36":{
      "scriptId":"u0"},
    "cb3fbfcf759140ac909e43f50a35277b":{
      "scriptId":"u1"},
    "e1074868e5784de2b0be661dfd254774":{
      "scriptId":"u2"},
    "037b9a1ba8d74106b68bc6e3ffec3693":{
      "scriptId":"u3"},
    "963b488b3f3d44c6b7fca0bd2640e65e":{
      "scriptId":"u4"},
    "cc67f58a104949b8b799e44b5032cf5f":{
      "scriptId":"u5"}}});